[functions.refresh-pass]
verify_jwt = true

[functions.bits-connect]
verify_jwt = true

[functions.twitch-eventsub]
verify_jwt = false

[functions.twitch-ads]
verify_jwt = true

[functions.store-asset]
verify_jwt = true
