/* generated by tools/stamp-build.js — do not hand-edit */
window.PLAY_BUILD = "20260917-rc11";
window.PLAY_SPRITE_BUILD = "20260916-sp1";
window.PLAY_LOCATION_BUILD = "20260916-loc1";
window.PLAY_GIT_COMMIT = "624ec7b";
window.PLAY_DEPLOYED_AT = "2026-09-17T06:35:23.794Z";
