/* generated by tools/stamp-build.js — do not hand-edit */
window.PLAY_BUILD = "20260919-rc30";
window.PLAY_SPRITE_BUILD = "20260919-items1";
window.PLAY_LOCATION_BUILD = "20260916-loc1";
window.PLAY_GIT_COMMIT = "70ed9c1";
window.PLAY_DEPLOYED_AT = "2026-09-19T18:47:45.198Z";
