/* generated by tools/stamp-build.js — do not hand-edit */
window.PLAY_BUILD = "20260919-rc27";
window.PLAY_SPRITE_BUILD = "20260919-items1";
window.PLAY_LOCATION_BUILD = "20260916-loc1";
window.PLAY_GIT_COMMIT = "f713449";
window.PLAY_DEPLOYED_AT = "2026-09-19T06:14:44.355Z";
