"""Generate the canonical capture seed migrations from tools/capture_data.json.

Re-running produces identical files, and the SQL itself is idempotent
(insert ... on conflict do update), so it is safe to apply repeatedly.
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DATA = json.load(open(os.path.join(HERE, "capture_data.json"), encoding="utf-8"))
MIG = os.path.join(ROOT, "supabase", "migrations")

# key -> (capture multiplier, tier, rarity, shop price per berry, capture enabled, store)
BERRY_RPG = {
    "oran":   (1.05, "common", "common", 5, True, True),
    "pecha":  (1.05, "common", "common", 5, True, True),
    "cheri":  (1.05, "common", "common", 5, True, True),
    "chesto": (1.05, "common", "common", 5, True, True),
    "rawst":  (1.05, "common", "common", 5, True, True),
    "aspear": (1.05, "common", "common", 5, True, True),
    "nanab":  (1.05, "common", "common", 5, True, True),
    "pinap":  (1.05, "common", "common", 6, True, True),
    "sitrus": (1.10, "better", "uncommon", 10, True, True),
    "lum":    (1.10, "better", "uncommon", 10, True, True),
    "persim": (1.10, "better", "uncommon", 10, False, False),
    "figy":   (1.15, "specialty", "rare", 14, False, False),
    "wiki":   (1.15, "specialty", "rare", 14, False, False),
    "mago":   (1.15, "specialty", "rare", 14, False, False),
    "aguav":  (1.15, "specialty", "rare", 14, False, False),
    "iapapa": (1.15, "specialty", "rare", 14, False, False),
    "razz":   (1.15, "specialty", "rare", 14, True, True),
    "bluk":   (1.05, "common", "common", 5, False, False),
    "wepear": (1.05, "common", "common", 5, False, False),
    "leppa":  (1.05, "common", "common", 5, False, False),
}

# Berries that only exist in Pokemon GO, so PokeAPI has no record of them.
GO_BERRIES = [
    {
        "key": "goldenrazz", "slug": "golden-razz", "name": "Golden Razz Berry",
        "sprite": "razz-berry.png", "multiplier": 1.30, "tier": "premium",
        "rarity": "epic", "price": 45, "reward": 0.0, "capture": True, "store": True,
        "canonical_flavor_text": "A shimmering Razz Berry from a far-off region. Wild Pokémon find it irresistible.",
        "rpg": "A rare golden Berry that makes a wild Pokémon much easier to catch.",
    },
    {
        "key": "silverpinap", "slug": "silver-pinap", "name": "Silver Pinap Berry",
        "sprite": "pinap-berry.png", "multiplier": 1.20, "tier": "premium",
        "rarity": "rare", "price": 24, "reward": 0.25, "capture": True, "store": True,
        "canonical_flavor_text": "A gleaming Pinap Berry. It helps with the catch and leaves a little something behind.",
        "rpg": "Makes a wild Pokémon easier to catch and sweetens the reward if you succeed.",
    },
]

RPG_DESCRIPTIONS = {
    1.05: "A tasty Berry that makes a wild Pokémon a little easier to catch.",
    1.10: "A quality Berry that makes a wild Pokémon easier to catch.",
    1.15: "A rich Berry that makes a wild Pokémon noticeably easier to catch.",
}

REWARD_BONUS = {"pinap": 0.5}

# Berries whose custom RPG copy has to mention something the tier text cannot.
RPG_OVERRIDES = {
    "pinap": "Helps a little with the catch and pays a small bonus when you succeed.",
}


def q(value):
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def arr(values):
    return "array[" + ", ".join(q(v) for v in values) + "]::text[]"


def write_species():
    rows = []
    for m in DATA["species"]:
        rows.append("{dex}|{slug}|{catch}|{types}|{speed}|{weight}|{height}|{moon}|{legend}".format(
            dex=m["dex"], slug=m["slug"], catch=m["catch_rate"], types=",".join(m["types"]),
            speed=m["base_speed"], weight=m["weight_kg"], height=m["height_m"],
            moon="t" if m["moon_stone_family"] else "f",
            legend="t" if (m["is_legendary"] or m["is_mythical"]) else "f",
        ))
    body = """-- Canonical capture data for Kanto #001-#151, imported from PokeAPI.
-- Generated by tools/build_capture_migrations.py. Safe to re-run.

alter table public.species
  add column if not exists slug text,
  add column if not exists catch_rate int,
  add column if not exists types text[],
  add column if not exists base_speed int,
  add column if not exists weight_kg numeric,
  add column if not exists height_m numeric,
  add column if not exists moon_stone_family boolean not null default false,
  add column if not exists is_legendary boolean not null default false,
  -- Spawn rarity is deliberately separate from capture difficulty.
  add column if not exists spawn_weight numeric not null default 1;

create index if not exists species_catch_rate_idx on public.species (catch_rate);

-- dex | slug | catchRate | types | baseSpeed | weightKg | heightM | moonStoneFamily | legendary
-- species.name is not null, so the proposed row has to carry one even when the
-- conflict path wins. Existing display names are never overwritten below.
insert into public.species (dex, name, slug, catch_rate, types, base_speed, weight_kg, height_m, moon_stone_family, is_legendary)
select c[1]::int, initcap(replace(c[2], '-', ' ')), c[2], c[3]::int, string_to_array(c[4], ','),
       c[5]::int, c[6]::numeric, c[7]::numeric, c[8] = 't', c[9] = 't'
from (
  select string_to_array(line, '|') as c
  from unnest(array[
{rows}
  ]) as line
) src
on conflict (dex) do update set
  slug = excluded.slug,
  catch_rate = excluded.catch_rate,
  types = excluded.types,
  base_speed = excluded.base_speed,
  weight_kg = excluded.weight_kg,
  height_m = excluded.height_m,
  moon_stone_family = excluded.moon_stone_family,
  is_legendary = excluded.is_legendary;
""".format(rows=",\n".join("    '" + r + "'" for r in rows))
    path = os.path.join(MIG, "20260913030000_capture_species_data.sql")
    open(path, "w", encoding="utf-8", newline="\n").write(body)
    print("wrote", path, len(rows), "species")


def write_berries():
    rows = []
    for b in DATA["berries"]:
        cfg = BERRY_RPG[b["slug"]]
        multiplier, tier, rarity, price, capture, store = cfg
        key = "berry" if b["slug"] == "oran" else b["slug"]
        rows.append(
            "  ({key}, {slug}, {berry_id}, {item_id}, {item_slug}, {name}, {firmness}, {gift_type}, "
            "{gift_power}, {flavors}::jsonb, {sprite}, {effect}, {flavor_text}, {mult}, {reward}, "
            "{rpg}, {tier}, {rarity}, {price}, {sell}, true, {capture}, {store}, {sort})".format(
                key=q(key), slug=q(b["slug"]), berry_id=b["berry_id"], item_id=b["item_id"],
                item_slug=q(b["item_slug"]), name=q(b["display_name"]), firmness=q(b["firmness"]),
                gift_type=q(b["natural_gift_type"]), gift_power=b["natural_gift_power"],
                flavors=q(json.dumps(b["flavors"])), sprite=q(b["item_slug"] + ".png"),
                effect=q(b["effect"]), flavor_text=q(b["flavor_text"]),
                mult=multiplier, reward=REWARD_BONUS.get(b["slug"], 0),
                rpg=q(RPG_OVERRIDES.get(b["slug"], RPG_DESCRIPTIONS[multiplier])), tier=q(tier), rarity=q(rarity),
                price=price, sell=max(1, price // 2), capture=q(capture), store=q(store),
                sort=b["berry_id"] * 10,
            )
        )
    for g in GO_BERRIES:
        rows.append(
            "  ({key}, {slug}, null, null, null, {name}, null, null, null, '{{}}'::jsonb, {sprite}, "
            "null, {flavor_text}, {mult}, {reward}, {rpg}, {tier}, {rarity}, {price}, {sell}, true, "
            "{capture}, {store}, {sort})".format(
                key=q(g["key"]), slug=q(g["slug"]), name=q(g["name"]), sprite=q(g["sprite"]),
                flavor_text=q(g["canonical_flavor_text"]), mult=g["multiplier"], reward=g["reward"],
                rpg=q(g["rpg"]), tier=q(g["tier"]), rarity=q(g["rarity"]), price=g["price"],
                sell=max(1, g["price"] // 2), capture=q(g["capture"]), store=q(g["store"]),
                sort=900 + GO_BERRIES.index(g) * 10,
            )
        )

    body = """-- Canonical Berry metadata imported from PokeAPI plus this RPG's capture effects.
-- Generated by tools/build_capture_migrations.py. Safe to re-run: canonical fields are
-- refreshed, locally tuned RPG fields are only set when the row is first created.

insert into public.capture_berries (
  key, slug, berry_id, item_id, item_slug, name, firmness, natural_gift_type,
  natural_gift_power, flavors, sprite, canonical_effect, canonical_flavor_text,
  capture_multiplier, reward_bonus, rpg_description, tier, rarity, shop_price, sell_price,
  enabled, capture_enabled, store_available, sort_order
)
values
{rows}
on conflict (key) do update set
  slug = excluded.slug,
  berry_id = excluded.berry_id,
  item_id = excluded.item_id,
  item_slug = excluded.item_slug,
  name = excluded.name,
  firmness = excluded.firmness,
  natural_gift_type = excluded.natural_gift_type,
  natural_gift_power = excluded.natural_gift_power,
  flavors = excluded.flavors,
  sprite = coalesce(public.capture_berries.sprite, excluded.sprite),
  canonical_effect = excluded.canonical_effect,
  canonical_flavor_text = excluded.canonical_flavor_text,
  updated_at = now();
""".format(rows=",\n".join(rows))
    path = os.path.join(MIG, "20260913032000_capture_berry_import.sql")
    open(path, "w", encoding="utf-8", newline="\n").write(body)
    print("wrote", path, len(rows), "berries")


if __name__ == "__main__":
    write_species()
    write_berries()
