const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

const dir = path.join(__dirname, "..");
const configPath = path.join(dir, "build.json");
if (!fs.existsSync(configPath)) {
  console.error("BUILD VALIDATION FAILED\nMissing build.json");
  process.exit(1);
}
const config = JSON.parse(fs.readFileSync(configPath, "utf8"));
const APP = String(config.appBuild || "").trim();
const SPRITE = String(config.spriteBuild || "").trim();
const LOCATION = String(config.locationBuild || APP).trim();
if (!APP) {
  console.error("BUILD VALIDATION FAILED\nbuild.json.appBuild is empty");
  process.exit(1);
}

function gitCommit() {
  try {
    return String(execSync("git rev-parse --short HEAD", { cwd: dir, stdio: ["ignore", "pipe", "ignore"] })).trim();
  } catch (_) {
    return "";
  }
}

const commit = gitCommit();
const deployedAt = new Date().toISOString();

const buildJs = [
  "/* generated by tools/stamp-build.js — do not hand-edit */",
  `window.PLAY_BUILD = ${JSON.stringify(APP)};`,
  `window.PLAY_SPRITE_BUILD = ${JSON.stringify(SPRITE)};`,
  `window.PLAY_LOCATION_BUILD = ${JSON.stringify(LOCATION)};`,
  `window.PLAY_GIT_COMMIT = ${JSON.stringify(commit)};`,
  `window.PLAY_DEPLOYED_AT = ${JSON.stringify(deployedAt)};`,
  ""
].join("\n");
fs.writeFileSync(path.join(dir, "js", "build.js"), buildJs);

const variantsPath = path.join(dir, "js", "variants.js");
if (fs.existsSync(variantsPath)) {
  let variants = fs.readFileSync(variantsPath, "utf8");
  if (/window\.PLAY_SPRITE_BUILD\s*=/.test(variants)) {
    variants = variants.replace(/window\.PLAY_SPRITE_BUILD\s*=\s*(["'`])[^"'`]*\1/, `window.PLAY_SPRITE_BUILD = ${JSON.stringify(SPRITE)}`);
  } else {
    variants = `window.PLAY_SPRITE_BUILD = ${JSON.stringify(SPRITE)};\n${variants}`;
  }
  fs.writeFileSync(variantsPath, variants);
}

for (const name of fs.readdirSync(dir)) {
  if (!name.endsWith(".html")) continue;
  const file = path.join(dir, name);
  let html = fs.readFileSync(file, "utf8");
  if (!/js\/build\.js/.test(html) && /js\/config\.js/.test(html)) {
    html = html.replace(/<script src="js\/config\.js(?:\?v=[^"]*)?"><\/script>/, (m) => `${m}\n<script src="js/build.js?v=${APP}"></script>`);
  }
  if (/js\/build\.js/.test(html) && !/js\/build-client\.js/.test(html)) {
    html = html.replace(/<script src="js\/build\.js(?:\?v=[^"]*)?"><\/script>/, (m) => `${m}\n<script src="js/build-client.js?v=${APP}"></script>`);
  }
  if (/js\/game\.js/.test(html) && !/js\/variants\.js/.test(html)) {
    html = html.replace(/<script src="js\/game\.js(?:\?v=[^"]*)?"><\/script>/, (m) => `<script src="js/variants.js?v=${APP}"></script>\n${m}`);
  }
  if (/js\/game\.js/.test(html) && !/js\/play-present\.js/.test(html)) {
    html = html.replace(/<script src="js\/game\.js(?:\?v=[^"]*)?"><\/script>/, (m) => `${m}\n<script src="js/play-present.js?v=${APP}"></script>`);
  }
  if (/js\/game\.js/.test(html) && !/play-encounter-state/.test(html)) {
    html = html.replace(/<script src="js\/game\.js(?:\?v=[^"]*)?"><\/script>/, (m) => `${m}\n<script src="js/play-encounter-state.js?v=${APP}"></script>`);
  }
  html = html.replace(/(href|src)="((?:css|js)\/[^"?]+)(?:\?v=[^"]*)?"/g, `$1="$2?v=${APP}"`);
  fs.writeFileSync(file, html);
}

fs.writeFileSync(path.join(dir, "build-manifest.json"), `${JSON.stringify({
  appBuild: APP,
  spriteBuild: SPRITE,
  locationBuild: LOCATION,
  gitCommit: commit,
  deployedAt
}, null, 2)}\n`);

console.log(`stamped app=${APP} sprite=${SPRITE} location=${LOCATION} git=${commit || "none"}`);
