-- Compact form seed: base rows from species + 85 Gen-1 EVENT_READY non-base forms.

delete from public.pokemon_forms;

insert into public.pokemon_forms (
  pokemon_form_id, dex, form_key, form_label, kind, is_base,
  has_front, has_shiny_front, has_female_front, has_back,
  admin_targetable, event_targetable, normal_encounter_enabled, asset_status, origin_gen1
)
select
  s.dex, s.dex, 'base', 'Base', 'base', true,
  true, true, false, true,
  true, true,
  case when s.dex between 1 and 151 and s.dex not in (144,145,146,150,151) then true else false end,
  'ready',
  (s.dex <= 151)
from public.species s
where s.dex between 1 and 1025;

insert into public.pokemon_forms (
  pokemon_form_id, dex, form_key, form_label, kind, is_base,
  has_front, has_shiny_front, has_female_front, has_back,
  admin_targetable, event_targetable, normal_encounter_enabled, asset_status, origin_gen1
) values
(10033, 3, 'mega', 'Mega', 'mega', false, true, true, false, true, true, true, false, 'ready', true),
(10034, 6, 'mega-x', 'Mega X', 'mega', false, true, true, false, true, true, true, false, 'ready', true),
(10035, 6, 'mega-y', 'Mega Y', 'mega', false, true, true, false, true, true, true, false, 'ready', true),
(10036, 9, 'mega', 'Mega', 'mega', false, true, true, false, true, true, true, false, 'ready', true),
(10037, 65, 'mega', 'Mega', 'mega', false, true, true, false, true, true, true, false, 'ready', true),
(10038, 94, 'mega', 'Mega', 'mega', false, true, true, false, true, true, true, false, 'ready', true),
(10039, 115, 'mega', 'Mega', 'mega', false, true, true, false, true, true, true, false, 'ready', true),
(10040, 127, 'mega', 'Mega', 'mega', false, true, true, false, true, true, true, false, 'ready', true),
(10041, 130, 'mega', 'Mega', 'mega', false, true, true, false, true, true, true, false, 'ready', true),
(10042, 142, 'mega', 'Mega', 'mega', false, true, true, false, true, true, true, false, 'ready', true),
(10043, 150, 'mega-x', 'Mega X', 'mega', false, true, true, false, true, true, true, false, 'ready', true),
(10044, 150, 'mega-y', 'Mega Y', 'mega', false, true, true, false, true, true, true, false, 'ready', true),
(10071, 80, 'mega', 'Mega', 'mega', false, true, true, false, true, true, true, false, 'ready', true),
(10073, 18, 'mega', 'Mega', 'mega', false, true, true, false, true, true, true, false, 'ready', true),
(10080, 25, 'rock-star', 'Rock Star', 'costume', false, true, true, false, true, true, true, false, 'ready', true),
(10081, 25, 'belle', 'Belle', 'costume', false, true, true, false, true, true, true, false, 'ready', true),
(10082, 25, 'pop-star', 'Pop Star', 'costume', false, true, true, false, true, true, true, false, 'ready', true),
(10083, 25, 'phd', 'PhD', 'costume', false, true, true, false, true, true, true, false, 'ready', true),
(10084, 25, 'libre', 'Libre', 'costume', false, true, true, false, false, true, true, false, 'ready', true),
(10085, 25, 'cosplay', 'Cosplay', 'costume', false, true, true, false, true, true, true, false, 'ready', true),
(10090, 15, 'mega', 'Mega', 'mega', false, true, true, false, true, true, true, false, 'ready', true),
(10091, 19, 'alolan', 'Alolan', 'regional', false, true, true, false, true, true, true, false, 'ready', true),
(10092, 20, 'alolan', 'Alolan', 'regional', false, true, true, false, true, true, true, false, 'ready', true),
(10093, 20, 'totem-alola', 'Totem Alola', 'other', false, true, true, false, true, true, true, false, 'ready', true),
(10094, 25, 'original-cap', 'Original Cap', 'costume', false, true, true, false, true, true, true, false, 'ready', true),
(10095, 25, 'hoenn-cap', 'Hoenn Cap', 'costume', false, true, true, false, true, true, true, false, 'ready', true),
(10096, 25, 'sinnoh-cap', 'Sinnoh Cap', 'costume', false, true, true, false, true, true, true, false, 'ready', true),
(10097, 25, 'unova-cap', 'Unova Cap', 'costume', false, true, true, false, true, true, true, false, 'ready', true),
(10098, 25, 'kalos-cap', 'Kalos Cap', 'costume', false, true, true, false, true, true, true, false, 'ready', true),
(10099, 25, 'alola-cap', 'Alola Cap', 'costume', false, true, true, false, true, true, true, false, 'ready', true),
(10100, 26, 'alolan', 'Alolan', 'regional', false, true, true, false, true, true, true, false, 'ready', true),
(10101, 27, 'alolan', 'Alolan', 'regional', false, true, true, false, true, true, true, false, 'ready', true),
(10102, 28, 'alolan', 'Alolan', 'regional', false, true, true, false, true, true, true, false, 'ready', true),
(10103, 37, 'alolan', 'Alolan', 'regional', false, true, true, false, true, true, true, false, 'ready', true),
(10104, 38, 'alolan', 'Alolan', 'regional', false, true, true, false, true, true, true, false, 'ready', true),
(10105, 50, 'alolan', 'Alolan', 'regional', false, true, true, false, true, true, true, false, 'ready', true),
(10106, 51, 'alolan', 'Alolan', 'regional', false, true, true, false, true, true, true, false, 'ready', true),
(10107, 52, 'alolan', 'Alolan', 'regional', false, true, true, false, true, true, true, false, 'ready', true),
(10108, 53, 'alolan', 'Alolan', 'regional', false, true, true, false, true, true, true, false, 'ready', true),
(10109, 74, 'alolan', 'Alolan', 'regional', false, true, true, false, true, true, true, false, 'ready', true),
(10110, 75, 'alolan', 'Alolan', 'regional', false, true, true, false, true, true, true, false, 'ready', true),
(10111, 76, 'alolan', 'Alolan', 'regional', false, true, true, false, true, true, true, false, 'ready', true),
(10112, 88, 'alolan', 'Alolan', 'regional', false, true, true, false, true, true, true, false, 'ready', true),
(10113, 89, 'alolan', 'Alolan', 'regional', false, true, true, false, true, true, true, false, 'ready', true),
(10114, 103, 'alolan', 'Alolan', 'regional', false, true, true, false, true, true, true, false, 'ready', true),
(10115, 105, 'alolan', 'Alolan', 'regional', false, true, true, false, true, true, true, false, 'ready', true),
(10148, 25, 'partner-cap', 'Partner Cap', 'costume', false, true, true, false, true, true, true, false, 'ready', true),
(10149, 105, 'totem', 'Totem', 'other', false, true, true, false, true, true, true, false, 'ready', true),
(10158, 25, 'starter', 'Starter', 'costume', false, true, true, false, true, true, true, false, 'ready', true),
(10159, 133, 'starter', 'Starter', 'costume', false, true, true, false, true, true, true, false, 'ready', true),
(10160, 25, 'world-cap', 'World Cap', 'costume', false, true, true, false, true, true, true, false, 'ready', true),
(10161, 52, 'galarian', 'Galarian', 'regional', false, true, true, false, true, true, true, false, 'ready', true),
(10162, 77, 'galarian', 'Galarian', 'regional', false, true, true, false, true, true, true, false, 'ready', true),
(10163, 78, 'galarian', 'Galarian', 'regional', false, true, true, false, true, true, true, false, 'ready', true),
(10164, 79, 'galarian', 'Galarian', 'regional', false, true, true, false, true, true, true, false, 'ready', true),
(10165, 80, 'galarian', 'Galarian', 'regional', false, true, true, false, true, true, true, false, 'ready', true),
(10166, 83, 'galarian', 'Galarian', 'regional', false, true, true, false, true, true, true, false, 'ready', true),
(10167, 110, 'galarian', 'Galarian', 'regional', false, true, true, false, true, true, true, false, 'ready', true),
(10168, 122, 'galarian', 'Galarian', 'regional', false, true, true, false, true, true, true, false, 'ready', true),
(10169, 144, 'galarian', 'Galarian', 'regional', false, true, true, false, true, true, true, false, 'ready', true),
(10170, 145, 'galarian', 'Galarian', 'regional', false, true, true, false, true, true, true, false, 'ready', true),
(10171, 146, 'galarian', 'Galarian', 'regional', false, true, true, false, true, true, true, false, 'ready', true),
(10195, 3, 'gigantamax', 'Gigantamax', 'gigantamax', false, true, true, false, false, true, true, false, 'ready', true),
(10196, 6, 'gigantamax', 'Gigantamax', 'gigantamax', false, true, true, false, true, true, true, false, 'ready', true),
(10197, 9, 'gigantamax', 'Gigantamax', 'gigantamax', false, true, true, false, false, true, true, false, 'ready', true),
(10198, 12, 'gigantamax', 'Gigantamax', 'gigantamax', false, true, true, false, true, true, true, false, 'ready', true),
(10199, 25, 'gigantamax', 'Gigantamax', 'gigantamax', false, true, true, false, true, true, true, false, 'ready', true),
(10200, 52, 'gigantamax', 'Gigantamax', 'gigantamax', false, true, true, false, true, true, true, false, 'ready', true),
(10201, 68, 'gigantamax', 'Gigantamax', 'gigantamax', false, true, true, false, true, true, true, false, 'ready', true),
(10202, 94, 'gigantamax', 'Gigantamax', 'gigantamax', false, true, true, false, true, true, true, false, 'ready', true),
(10203, 99, 'gigantamax', 'Gigantamax', 'gigantamax', false, true, true, false, true, true, true, false, 'ready', true),
(10204, 131, 'gigantamax', 'Gigantamax', 'gigantamax', false, true, true, false, true, true, true, false, 'ready', true),
(10205, 133, 'gigantamax', 'Gigantamax', 'gigantamax', false, true, true, false, true, true, true, false, 'ready', true),
(10206, 143, 'gigantamax', 'Gigantamax', 'gigantamax', false, true, true, false, true, true, true, false, 'ready', true),
(10229, 58, 'hisuian', 'Hisuian', 'regional', false, true, true, false, true, true, true, false, 'ready', true),
(10230, 59, 'hisuian', 'Hisuian', 'regional', false, true, true, false, true, true, true, false, 'ready', true),
(10231, 100, 'hisuian', 'Hisuian', 'regional', false, true, true, false, true, true, true, false, 'ready', true),
(10232, 101, 'hisuian', 'Hisuian', 'regional', false, true, true, false, true, true, true, false, 'ready', true),
(10250, 128, 'paldea-combat-breed', 'Paldea Combat Breed', 'regional', false, true, true, false, true, true, true, false, 'ready', true),
(10251, 128, 'paldea-blaze-breed', 'Paldea Blaze Breed', 'regional', false, true, true, false, true, true, true, false, 'ready', true),
(10252, 128, 'paldea-aqua-breed', 'Paldea Aqua Breed', 'regional', false, true, true, false, true, true, true, false, 'ready', true),
(10278, 36, 'mega', 'Mega', 'mega', false, true, true, false, true, true, true, false, 'ready', true),
(10279, 71, 'mega', 'Mega', 'mega', false, true, true, false, true, true, true, false, 'ready', true),
(10280, 121, 'mega', 'Mega', 'mega', false, true, true, false, true, true, true, false, 'ready', true),
(10281, 149, 'mega', 'Mega', 'mega', false, true, true, false, true, true, true, false, 'ready', true);
