-- rc107 team backgrounds: free expansion + owner-supplied scenes
insert into public.progression_cosmetics (id, kind, name, description, how_to, requirement, sort_order, enabled, starter)
values
  ('team-bg-starlight-gradient', 'team_background', 'ST★RLIGHT Gradient', 'ST★RLIGHT Gradient', 'Available to every Trainer.', '{"type":"starter"}'::jsonb, 200, true, true),
  ('team-bg-pokedex-grid', 'team_background', 'Pokédex Grid', 'Pokédex Grid', 'Available to every Trainer.', '{"type":"starter"}'::jsonb, 201, true, true),
  ('team-bg-research-lab', 'team_background', 'Research Lab', 'Research Lab', 'Available to every Trainer.', '{"type":"starter"}'::jsonb, 202, true, true),
  ('team-bg-battle-stage', 'team_background', 'Battle Stage', 'Battle Stage', 'Available to every Trainer.', '{"type":"starter"}'::jsonb, 203, true, true),
  ('team-bg-gen1-mono', 'team_background', 'ST★RLIGHT — Gen I', 'ST★RLIGHT — Gen I', 'Available to every Trainer.', '{"type":"starter"}'::jsonb, 204, true, true),
  ('team-bg-gen2-color', 'team_background', 'ST★RLIGHT — Gen II', 'ST★RLIGHT — Gen II', 'Available to every Trainer.', '{"type":"starter"}'::jsonb, 205, true, true),
  ('team-bg-gen3-gba', 'team_background', 'ST★RLIGHT — Gen III', 'ST★RLIGHT — Gen III', 'Available to every Trainer.', '{"type":"starter"}'::jsonb, 206, true, true),
  ('team-bg-gen4-ds', 'team_background', 'ST★RLIGHT — Gen IV', 'ST★RLIGHT — Gen IV', 'Available to every Trainer.', '{"type":"starter"}'::jsonb, 207, true, true),
  ('team-bg-retro-battle', 'team_background', 'ST★RLIGHT — Retro Battle', 'ST★RLIGHT — Retro Battle', 'Available to every Trainer.', '{"type":"starter"}'::jsonb, 208, true, true),
  ('team-bg-kanto-route', 'team_background', 'ST★RLIGHT — Kanto Route', 'ST★RLIGHT — Kanto Route', 'Available to every Trainer.', '{"type":"starter"}'::jsonb, 209, true, true),
  ('team-bg-pallet-town', 'team_background', 'Pallet Town', 'Pallet Town', 'Available to every Trainer.', '{"type":"starter"}'::jsonb, 210, true, true),
  ('team-bg-viridian-forest', 'team_background', 'Viridian Forest', 'Viridian Forest', 'Available to every Trainer.', '{"type":"starter"}'::jsonb, 211, true, true),
  ('team-bg-route-1', 'team_background', 'Route 1', 'Route 1', 'Available to every Trainer.', '{"type":"starter"}'::jsonb, 212, true, true),
  ('team-bg-route-2', 'team_background', 'Route 2', 'Route 2', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 213, true, false),
  ('team-bg-mt-moon', 'team_background', 'Mt. Moon', 'Mt. Moon', 'Available to every Trainer.', '{"type":"starter"}'::jsonb, 214, true, true),
  ('team-bg-cerulean-cave', 'team_background', 'Cerulean Cave', 'Cerulean Cave', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 215, true, false),
  ('team-bg-digletts-cave', 'team_background', 'Diglett''s Cave', 'Diglett''s Cave', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 216, true, false),
  ('team-bg-rock-tunnel', 'team_background', 'Rock Tunnel', 'Rock Tunnel', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 217, true, false),
  ('team-bg-seafoam-islands', 'team_background', 'Seafoam Islands', 'Seafoam Islands', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 218, true, false),
  ('team-bg-saffron-city', 'team_background', 'Saffron City', 'Saffron City', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 219, true, false),
  ('team-bg-cinnabar-lab', 'team_background', 'Cinnabar Lab', 'Cinnabar Lab', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 220, true, false),
  ('team-bg-safari-zone', 'team_background', 'Safari Zone', 'Safari Zone', 'Available to every Trainer.', '{"type":"starter"}'::jsonb, 221, true, true),
  ('team-bg-power-plant', 'team_background', 'Power Plant', 'Power Plant', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 222, true, false),
  ('team-bg-victory-road', 'team_background', 'Victory Road', 'Victory Road', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 223, true, false),
  ('team-bg-owner-town001', 'team_background', 'Hometown Lane', 'Hometown Lane', 'Available to every Trainer.', '{"type":"starter"}'::jsonb, 224, true, true),
  ('team-bg-owner-town002', 'team_background', 'Village Square', 'Village Square', 'Available to every Trainer.', '{"type":"starter"}'::jsonb, 225, true, true),
  ('team-bg-owner-town003', 'team_background', 'Lakeside Town', 'Lakeside Town', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 226, true, false),
  ('team-bg-owner-town004', 'team_background', 'Harbor Town', 'Harbor Town', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 227, true, false),
  ('team-bg-owner-town005', 'team_background', 'Market Town', 'Market Town', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 228, true, false),
  ('team-bg-owner-town006', 'team_background', 'Hillside Town', 'Hillside Town', 'Available to every Trainer.', '{"type":"starter"}'::jsonb, 229, true, true),
  ('team-bg-owner-town007', 'team_background', 'Garden Town', 'Garden Town', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 230, true, false),
  ('team-bg-owner-town008', 'team_background', 'River Town', 'River Town', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 231, true, false),
  ('team-bg-owner-town009', 'team_background', 'Farmstead', 'Farmstead', 'Available to every Trainer.', '{"type":"starter"}'::jsonb, 232, true, true),
  ('team-bg-owner-town010', 'team_background', 'Coastal Town', 'Coastal Town', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 233, true, false),
  ('team-bg-owner-town011', 'team_background', 'Pokémon Center Outlook', 'Pokémon Center Outlook', 'Available to every Trainer.', '{"type":"starter"}'::jsonb, 234, true, true),
  ('team-bg-owner-road001', 'team_background', 'Sunny Route', 'Sunny Route', 'Available to every Trainer.', '{"type":"starter"}'::jsonb, 235, true, true),
  ('team-bg-owner-road002', 'team_background', 'Grassy Route', 'Grassy Route', 'Available to every Trainer.', '{"type":"starter"}'::jsonb, 236, true, true),
  ('team-bg-owner-road003', 'team_background', 'Forest Path', 'Forest Path', 'Available to every Trainer.', '{"type":"starter"}'::jsonb, 237, true, true),
  ('team-bg-owner-road004', 'team_background', 'Meadow Path', 'Meadow Path', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 238, true, false),
  ('team-bg-owner-road005', 'team_background', 'Pine Route', 'Pine Route', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 239, true, false),
  ('team-bg-owner-road006', 'team_background', 'Cliffside Path', 'Cliffside Path', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 240, true, false),
  ('team-bg-owner-road007', 'team_background', 'Tall Grass Trail', 'Tall Grass Trail', 'Available to every Trainer.', '{"type":"starter"}'::jsonb, 241, true, true),
  ('team-bg-owner-road008', 'team_background', 'Woodland Trail', 'Woodland Trail', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 242, true, false),
  ('team-bg-owner-road009', 'team_background', 'Stream Crossing', 'Stream Crossing', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 243, true, false),
  ('team-bg-owner-road010', 'team_background', 'Scenic Overlook', 'Scenic Overlook', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 244, true, false),
  ('team-bg-owner-road011', 'team_background', 'Canyon Road', 'Canyon Road', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 245, true, false),
  ('team-bg-owner-road012', 'team_background', 'Dusty Canyon', 'Dusty Canyon', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 246, true, false),
  ('team-bg-owner-road013', 'team_background', 'Highland Path', 'Highland Path', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 247, true, false),
  ('team-bg-owner-road014', 'team_background', 'Verdant Terrace', 'Verdant Terrace', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 248, true, false),
  ('team-bg-owner-road015', 'team_background', 'Evergreen Route', 'Evergreen Route', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 249, true, false),
  ('team-bg-owner-road016', 'team_background', 'Flowering Path', 'Flowering Path', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 250, true, false),
  ('team-bg-owner-road017', 'team_background', 'Gatehouse Road', 'Gatehouse Road', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 251, true, false),
  ('team-bg-owner-road018', 'team_background', 'Park Path', 'Park Path', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 252, true, false),
  ('team-bg-owner-road019', 'team_background', 'Training Yard', 'Training Yard', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 253, true, false),
  ('team-bg-owner-road020', 'team_background', 'Practice Field', 'Practice Field', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 254, true, false),
  ('team-bg-owner-road021', 'team_background', 'River Fence Route', 'River Fence Route', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 255, true, false),
  ('team-bg-owner-road022', 'team_background', 'Cave Mouth Road', 'Cave Mouth Road', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 256, true, false),
  ('team-bg-owner-road023', 'team_background', 'Mountain Approach', 'Mountain Approach', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 257, true, false),
  ('team-bg-owner-road024', 'team_background', 'Layered Cliffs', 'Layered Cliffs', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 258, true, false),
  ('team-bg-owner-road025', 'team_background', 'Forest Edge', 'Forest Edge', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 259, true, false),
  ('team-bg-owner-r002g0101', 'team_background', 'Torchlit Chamber', 'Torchlit Chamber', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 260, true, false),
  ('team-bg-owner-r004d0101', 'team_background', 'Icy Cavern', 'Icy Cavern', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 261, true, false),
  ('team-bg-owner-r010d0101', 'team_background', 'Power Plant Floor', 'Power Plant Floor', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 262, true, false),
  ('team-bg-owner-r010r0101', 'team_background', 'Electric Lab', 'Electric Lab', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 263, true, false),
  ('team-bg-owner-r011d0101', 'team_background', 'Sandy Cave', 'Sandy Cave', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 264, true, false),
  ('team-bg-owner-r020d0101', 'team_background', 'Crater Cavern', 'Crater Cavern', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 265, true, false),
  ('team-bg-owner-r023d0101', 'team_background', 'Canyon Arena', 'Canyon Arena', 'Coming soon — unlocks through future Trainer rewards.', '{"type":"admin"}'::jsonb, 266, true, false)
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description,
  how_to = excluded.how_to,
  requirement = excluded.requirement,
  sort_order = excluded.sort_order,
  enabled = excluded.enabled,
  starter = excluded.starter;

insert into public.trainer_cosmetics (user_id, cosmetic_id, source)
select p.id, c.id, 'starter'
  from public.profiles p
  cross join public.progression_cosmetics c
 where c.kind = 'team_background' and c.starter and c.enabled
on conflict do nothing;
