-- Catalog every known Kanto 3D Front form. Only base sprites are enabled in play.
create table if not exists public.species_forms (
  dex int not null references public.species(dex),
  form_key text not null,
  form_label text not null,
  kind text not null,
  gender text not null default '',
  shiny boolean not null default false,
  source_set text not null,
  filename text not null,
  enabled_in_play boolean not null default false,
  primary key (dex, form_key, gender, shiny)
);
comment on table public.species_forms is 'Known Kanto 3D Front forms from ProjectPokemon. Alt forms are cataloged for later and are not implemented in play.';
alter table public.species_forms enable row level security;
drop policy if exists species_forms_read on public.species_forms;
create policy species_forms_read on public.species_forms for select to anon, authenticated using (true);
revoke all on public.species_forms from anon, authenticated;
grant select on public.species_forms to anon, authenticated;

insert into public.species_forms (dex, form_key, form_label, kind, gender, shiny, source_set, filename, enabled_in_play)
values
  (1, 'base', 'Base', 'base', '', false, 'Legacy3D', '001_Bulbasaur_Base_Normal_Front.gif', true),
  (1, 'base', 'Base', 'base', '', true, 'Legacy3D', '001_Bulbasaur_Base_Shiny_Front.gif', true),
  (2, 'base', 'Base', 'base', '', false, 'Legacy3D', '002_Ivysaur_Base_Normal_Front.gif', true),
  (2, 'base', 'Base', 'base', '', true, 'Legacy3D', '002_Ivysaur_Base_Shiny_Front.gif', true),
  (3, 'gigantamax', 'Gigantamax', 'gigantamax', '', false, 'SWSH', '003_Venusaur_Gigantamax_Normal_Front.gif', false),
  (3, 'gigantamax', 'Gigantamax', 'gigantamax', '', true, 'SWSH', '003_Venusaur_Gigantamax_Shiny_Front.gif', false),
  (3, 'base', 'Base', 'base', 'female', false, 'Legacy3D', '003_Venusaur_Base_Female_Normal_Front.gif', true),
  (3, 'base', 'Base', 'base', 'female', true, 'Legacy3D', '003_Venusaur_Base_Female_Shiny_Front.gif', true),
  (3, 'base', 'Base', 'base', 'male', false, 'Legacy3D', '003_Venusaur_Base_Male_Normal_Front.gif', true),
  (3, 'base', 'Base', 'base', 'male', true, 'Legacy3D', '003_Venusaur_Base_Male_Shiny_Front.gif', true),
  (3, 'mega', 'Mega', 'mega', '', false, 'Legacy3D', '003_Venusaur_Mega_Normal_Front.gif', false),
  (3, 'mega', 'Mega', 'mega', '', true, 'Legacy3D', '003_Venusaur_Mega_Shiny_Front.gif', false),
  (4, 'base', 'Base', 'base', '', false, 'SWSH', '004_Charmander_Base_Normal_Front.gif', true),
  (4, 'base', 'Base', 'base', '', true, 'SWSH', '004_Charmander_Base_Shiny_Front.gif', true),
  (5, 'base', 'Base', 'base', '', false, 'SWSH', '005_Charmeleon_Base_Normal_Front.gif', true),
  (5, 'base', 'Base', 'base', '', true, 'SWSH', '005_Charmeleon_Base_Shiny_Front.gif', true),
  (6, 'base', 'Base', 'base', '', false, 'SWSH', '006_Charizard_Base_Normal_Front.gif', true),
  (6, 'base', 'Base', 'base', '', true, 'SWSH', '006_Charizard_Base_Shiny_Front.gif', true),
  (6, 'gigantamax', 'Gigantamax', 'gigantamax', '', false, 'SWSH', '006_Charizard_Gigantamax_Normal_Front.gif', false),
  (6, 'gigantamax', 'Gigantamax', 'gigantamax', '', true, 'SWSH', '006_Charizard_Gigantamax_Shiny_Front.gif', false),
  (6, 'mega-x', 'Mega X', 'mega', '', false, 'Legacy3D', '006_Charizard_MegaX_Normal_Front.gif', false),
  (6, 'mega-x', 'Mega X', 'mega', '', true, 'Legacy3D', '006_Charizard_MegaX_Shiny_Front.gif', false),
  (6, 'mega-y', 'Mega Y', 'mega', '', false, 'Legacy3D', '006_Charizard_MegaY_Normal_Front.gif', false),
  (6, 'mega-y', 'Mega Y', 'mega', '', true, 'Legacy3D', '006_Charizard_MegaY_Shiny_Front.gif', false),
  (7, 'base', 'Base', 'base', '', false, 'Legacy3D', '007_Squirtle_Base_Normal_Front.gif', true),
  (7, 'base', 'Base', 'base', '', true, 'Legacy3D', '007_Squirtle_Base_Shiny_Front.gif', true),
  (8, 'base', 'Base', 'base', '', false, 'Legacy3D', '008_Wartortle_Base_Normal_Front.gif', true),
  (8, 'base', 'Base', 'base', '', true, 'Legacy3D', '008_Wartortle_Base_Shiny_Front.gif', true),
  (9, 'gigantamax', 'Gigantamax', 'gigantamax', '', false, 'SWSH', '009_Blastoise_Gigantamax_Normal_Front.gif', false),
  (9, 'gigantamax', 'Gigantamax', 'gigantamax', '', true, 'SWSH', '009_Blastoise_Gigantamax_Shiny_Front.gif', false),
  (9, 'base', 'Base', 'base', '', false, 'Legacy3D', '009_Blastoise_Base_Normal_Front.gif', true),
  (9, 'base', 'Base', 'base', '', true, 'Legacy3D', '009_Blastoise_Base_Shiny_Front.gif', true),
  (9, 'mega', 'Mega', 'mega', '', false, 'Legacy3D', '009_Blastoise_Mega_Normal_Front.gif', false),
  (9, 'mega', 'Mega', 'mega', '', true, 'Legacy3D', '009_Blastoise_Mega_Shiny_Front.gif', false),
  (10, 'base', 'Base', 'base', '', false, 'SWSH', '010_Caterpie_Base_Normal_Front.gif', true),
  (10, 'base', 'Base', 'base', '', true, 'SWSH', '010_Caterpie_Base_Shiny_Front.gif', true),
  (11, 'base', 'Base', 'base', '', false, 'SWSH', '011_Metapod_Base_Normal_Front.gif', true),
  (11, 'base', 'Base', 'base', '', true, 'SWSH', '011_Metapod_Base_Shiny_Front.gif', true),
  (12, 'base', 'Base', 'base', 'male', false, 'SWSH', '012_Butterfree_Base_Male_Normal_Front.gif', true),
  (12, 'base', 'Base', 'base', 'male', true, 'SWSH', '012_Butterfree_Base_Male_Shiny_Front.gif', true),
  (12, 'gigantamax', 'Gigantamax', 'gigantamax', '', false, 'SWSH', '012_Butterfree_Gigantamax_Normal_Front.gif', false),
  (12, 'gigantamax', 'Gigantamax', 'gigantamax', '', true, 'SWSH', '012_Butterfree_Gigantamax_Shiny_Front.gif', false),
  (13, 'base', 'Base', 'base', '', false, 'Legacy3D', '013_Weedle_Base_Normal_Front.gif', true),
  (13, 'base', 'Base', 'base', '', true, 'Legacy3D', '013_Weedle_Base_Shiny_Front.gif', true),
  (14, 'base', 'Base', 'base', '', false, 'Legacy3D', '014_Kakuna_Base_Normal_Front.gif', true),
  (14, 'base', 'Base', 'base', '', true, 'Legacy3D', '014_Kakuna_Base_Shiny_Front.gif', true),
  (15, 'base', 'Base', 'base', '', false, 'Legacy3D', '015_Beedrill_Base_Normal_Front.gif', true),
  (15, 'base', 'Base', 'base', '', true, 'Legacy3D', '015_Beedrill_Base_Shiny_Front.gif', true),
  (15, 'mega', 'Mega', 'mega', '', false, 'Legacy3D', '015_Beedrill_Mega_Normal_Front.gif', false),
  (15, 'mega', 'Mega', 'mega', '', true, 'Legacy3D', '015_Beedrill_Mega_Shiny_Front.gif', false),
  (16, 'base', 'Base', 'base', '', false, 'Legacy3D', '016_Pidgey_Base_Normal_Front.gif', true),
  (16, 'base', 'Base', 'base', '', true, 'Legacy3D', '016_Pidgey_Base_Shiny_Front.gif', true),
  (17, 'base', 'Base', 'base', '', false, 'Legacy3D', '017_Pidgeotto_Base_Normal_Front.gif', true),
  (17, 'base', 'Base', 'base', '', true, 'Legacy3D', '017_Pidgeotto_Base_Shiny_Front.gif', true),
  (18, 'base', 'Base', 'base', '', false, 'Legacy3D', '018_Pidgeot_Base_Normal_Front.gif', true),
  (18, 'base', 'Base', 'base', '', true, 'Legacy3D', '018_Pidgeot_Base_Shiny_Front.gif', true),
  (19, 'alolan', 'Alolan', 'regional', '', false, 'Legacy3D', '019_Rattata_Alolan_Normal_Front.gif', false),
  (19, 'alolan', 'Alolan', 'regional', '', true, 'Legacy3D', '019_Rattata_Alolan_Shiny_Front.gif', false),
  (19, 'base', 'Base', 'base', 'female', false, 'Legacy3D', '019_Rattata_Base_Female_Normal_Front.gif', true),
  (19, 'base', 'Base', 'base', 'female', true, 'Legacy3D', '019_Rattata_Base_Female_Shiny_Front.gif', true),
  (19, 'base', 'Base', 'base', 'male', false, 'Legacy3D', '019_Rattata_Base_Male_Normal_Front.gif', true),
  (19, 'base', 'Base', 'base', 'male', true, 'Legacy3D', '019_Rattata_Base_Male_Shiny_Front.gif', true),
  (20, 'alolan', 'Alolan', 'regional', '', false, 'Legacy3D', '020_Raticate_Alolan_Normal_Front.gif', false),
  (20, 'alolan', 'Alolan', 'regional', '', true, 'Legacy3D', '020_Raticate_Alolan_Shiny_Front.gif', false),
  (20, 'base', 'Base', 'base', 'female', false, 'Legacy3D', '020_Raticate_Base_Female_Normal_Front.gif', true),
  (20, 'base', 'Base', 'base', 'female', true, 'Legacy3D', '020_Raticate_Base_Female_Shiny_Front.gif', true),
  (20, 'base', 'Base', 'base', 'male', false, 'Legacy3D', '020_Raticate_Base_Male_Normal_Front.gif', true),
  (20, 'base', 'Base', 'base', 'male', true, 'Legacy3D', '020_Raticate_Base_Male_Shiny_Front.gif', true),
  (20, 'totem', 'Totem', 'other', '', false, 'Legacy3D', '020_Raticate_Totem_Normal_Front.gif', false),
  (20, 'totem', 'Totem', 'other', '', true, 'Legacy3D', '020_Raticate_Totem_Shiny_Front.gif', false),
  (21, 'base', 'Base', 'base', '', false, 'Legacy3D', '021_Spearow_Base_Normal_Front.gif', true),
  (21, 'base', 'Base', 'base', '', true, 'Legacy3D', '021_Spearow_Base_Shiny_Front.gif', true),
  (22, 'base', 'Base', 'base', '', false, 'Legacy3D', '022_Fearow_Base_Normal_Front.gif', true),
  (22, 'base', 'Base', 'base', '', true, 'Legacy3D', '022_Fearow_Base_Shiny_Front.gif', true),
  (23, 'base', 'Base', 'base', '', false, 'Legacy3D', '023_Ekans_Base_Normal_Front.gif', true),
  (23, 'base', 'Base', 'base', '', true, 'Legacy3D', '023_Ekans_Base_Shiny_Front.gif', true),
  (24, 'base', 'Base', 'base', '', false, 'Legacy3D', '024_Arbok_Base_Normal_Front.gif', true),
  (24, 'base', 'Base', 'base', '', true, 'Legacy3D', '024_Arbok_Base_Shiny_Front.gif', true),
  (25, 'alola-cap', 'Alola Cap', 'regional', 'male', false, 'SWSH', '025_Pikachu_AlolaCap_Male_Normal_Front.gif', false),
  (25, 'alola-cap', 'Alola Cap', 'regional', 'male', true, 'SWSH', '025_Pikachu_AlolaCap_Male_Shiny_Front.gif', false),
  (25, 'base', 'Base', 'base', 'male', false, 'SWSH', '025_Pikachu_Base_Male_Normal_Front.gif', true),
  (25, 'base', 'Base', 'base', 'male', true, 'SWSH', '025_Pikachu_Base_Male_Shiny_Front.gif', true),
  (25, 'gigantamax', 'Gigantamax', 'gigantamax', '', false, 'SWSH', '025_Pikachu_Gigantamax_Normal_Front.gif', false),
  (25, 'gigantamax', 'Gigantamax', 'gigantamax', '', true, 'SWSH', '025_Pikachu_Gigantamax_Shiny_Front.gif', false),
  (25, 'hoenn-cap', 'Hoenn Cap', 'costume', 'male', false, 'SWSH', '025_Pikachu_HoennCap_Male_Normal_Front.gif', false),
  (25, 'hoenn-cap', 'Hoenn Cap', 'costume', 'male', true, 'SWSH', '025_Pikachu_HoennCap_Male_Shiny_Front.gif', false),
  (25, 'kalos-cap', 'Kalos Cap', 'costume', 'male', false, 'SWSH', '025_Pikachu_KalosCap_Male_Normal_Front.gif', false),
  (25, 'kalos-cap', 'Kalos Cap', 'costume', 'male', true, 'SWSH', '025_Pikachu_KalosCap_Male_Shiny_Front.gif', false),
  (25, 'original-cap', 'Original Cap', 'costume', 'male', false, 'SWSH', '025_Pikachu_OriginalCap_Male_Normal_Front.gif', false),
  (25, 'original-cap', 'Original Cap', 'costume', 'male', true, 'SWSH', '025_Pikachu_OriginalCap_Male_Shiny_Front.gif', false),
  (25, 'partner-cap', 'Partner Cap', 'costume', 'male', false, 'SWSH', '025_Pikachu_PartnerCap_Male_Normal_Front.gif', false),
  (25, 'partner-cap', 'Partner Cap', 'costume', 'male', true, 'SWSH', '025_Pikachu_PartnerCap_Male_Shiny_Front.gif', false),
  (25, 'sinnoh-cap', 'Sinnoh Cap', 'costume', 'male', false, 'SWSH', '025_Pikachu_SinnohCap_Male_Normal_Front.gif', false),
  (25, 'sinnoh-cap', 'Sinnoh Cap', 'costume', 'male', true, 'SWSH', '025_Pikachu_SinnohCap_Male_Shiny_Front.gif', false),
  (25, 'unova-cap', 'Unova Cap', 'costume', 'male', false, 'SWSH', '025_Pikachu_UnovaCap_Male_Normal_Front.gif', false),
  (25, 'unova-cap', 'Unova Cap', 'costume', 'male', true, 'SWSH', '025_Pikachu_UnovaCap_Male_Shiny_Front.gif', false),
  (25, 'belle', 'Belle', 'costume', 'female', false, 'Legacy3D', '025_Pikachu_Belle_Female_Normal_Front.gif', false),
  (25, 'belle', 'Belle', 'costume', 'female', true, 'Legacy3D', '025_Pikachu_Belle_Female_Shiny_Front.gif', false),
  (25, 'cosplay', 'Cosplay', 'costume', 'female', false, 'Legacy3D', '025_Pikachu_Cosplay_Female_Normal_Front.gif', false),
  (25, 'cosplay', 'Cosplay', 'costume', 'female', true, 'Legacy3D', '025_Pikachu_Cosplay_Female_Shiny_Front.gif', false),
  (25, 'libre', 'Libre', 'costume', 'female', false, 'Legacy3D', '025_Pikachu_Libre_Female_Normal_Front.gif', false),
  (25, 'libre', 'Libre', 'costume', 'female', true, 'Legacy3D', '025_Pikachu_Libre_Female_Shiny_Front.gif', false),
  (25, 'ph-d', 'Ph D', 'other', 'female', false, 'Legacy3D', '025_Pikachu_PhD_Female_Normal_Front.gif', false),
  (25, 'ph-d', 'Ph D', 'other', 'female', true, 'Legacy3D', '025_Pikachu_PhD_Female_Shiny_Front.gif', false),
  (25, 'popstar', 'Popstar', 'costume', 'female', false, 'Legacy3D', '025_Pikachu_Popstar_Female_Normal_Front.gif', false),
  (25, 'popstar', 'Popstar', 'costume', 'female', true, 'Legacy3D', '025_Pikachu_Popstar_Female_Shiny_Front.gif', false),
  (25, 'rockstar', 'Rockstar', 'costume', 'female', false, 'Legacy3D', '025_Pikachu_Rockstar_Female_Normal_Front.gif', false),
  (25, 'rockstar', 'Rockstar', 'costume', 'female', true, 'Legacy3D', '025_Pikachu_Rockstar_Female_Shiny_Front.gif', false),
  (26, 'alolan', 'Alolan', 'regional', '', false, 'SWSH', '026_Raichu_Alolan_Normal_Front.gif', false),
  (26, 'alolan', 'Alolan', 'regional', '', true, 'SWSH', '026_Raichu_Alolan_Shiny_Front.gif', false),
  (26, 'base', 'Base', 'base', 'male', false, 'SWSH', '026_Raichu_Base_Male_Normal_Front.gif', true),
  (26, 'base', 'Base', 'base', 'male', true, 'SWSH', '026_Raichu_Base_Male_Shiny_Front.gif', true),
  (27, 'alolan', 'Alolan', 'regional', '', false, 'Legacy3D', '027_Sandshrew_Alolan_Normal_Front.gif', false),
  (27, 'alolan', 'Alolan', 'regional', '', true, 'Legacy3D', '027_Sandshrew_Alolan_Shiny_Front.gif', false),
  (27, 'base', 'Base', 'base', '', false, 'Legacy3D', '027_Sandshrew_Base_Normal_Front.gif', true),
  (27, 'base', 'Base', 'base', '', true, 'Legacy3D', '027_Sandshrew_Base_Shiny_Front.gif', true),
  (28, 'alolan', 'Alolan', 'regional', '', false, 'Legacy3D', '028_Sandslash_Alolan_Normal_Front.gif', false),
  (28, 'alolan', 'Alolan', 'regional', '', true, 'Legacy3D', '028_Sandslash_Alolan_Shiny_Front.gif', false),
  (28, 'base', 'Base', 'base', '', false, 'Legacy3D', '028_Sandslash_Base_Normal_Front.gif', true),
  (28, 'base', 'Base', 'base', '', true, 'Legacy3D', '028_Sandslash_Base_Shiny_Front.gif', true),
  (29, 'base', 'Base', 'base', '', false, 'Legacy3D', '029_NidoranF_Base_Normal_Front.gif', true),
  (29, 'base', 'Base', 'base', '', true, 'Legacy3D', '029_NidoranF_Base_Shiny_Front.gif', true),
  (30, 'base', 'Base', 'base', '', false, 'Legacy3D', '030_Nidorina_Base_Normal_Front.gif', true),
  (30, 'base', 'Base', 'base', '', true, 'Legacy3D', '030_Nidorina_Base_Shiny_Front.gif', true),
  (31, 'base', 'Base', 'base', '', false, 'Legacy3D', '031_Nidoqueen_Base_Normal_Front.gif', true),
  (31, 'base', 'Base', 'base', '', true, 'Legacy3D', '031_Nidoqueen_Base_Shiny_Front.gif', true),
  (32, 'base', 'Base', 'base', '', false, 'Legacy3D', '032_NidoranM_Base_Normal_Front.gif', true),
  (32, 'base', 'Base', 'base', '', true, 'Legacy3D', '032_NidoranM_Base_Shiny_Front.gif', true),
  (33, 'base', 'Base', 'base', '', false, 'Legacy3D', '033_Nidorino_Base_Normal_Front.gif', true),
  (33, 'base', 'Base', 'base', '', true, 'Legacy3D', '033_Nidorino_Base_Shiny_Front.gif', true),
  (34, 'base', 'Base', 'base', '', false, 'Legacy3D', '034_Nidoking_Base_Normal_Front.gif', true),
  (34, 'base', 'Base', 'base', '', true, 'Legacy3D', '034_Nidoking_Base_Shiny_Front.gif', true),
  (35, 'base', 'Base', 'base', '', false, 'SWSH', '035_Clefairy_Base_Normal_Front.gif', true),
  (35, 'base', 'Base', 'base', '', true, 'SWSH', '035_Clefairy_Base_Shiny_Front.gif', true),
  (36, 'base', 'Base', 'base', '', false, 'SWSH', '036_Clefable_Base_Normal_Front.gif', true),
  (36, 'base', 'Base', 'base', '', true, 'SWSH', '036_Clefable_Base_Shiny_Front.gif', true),
  (37, 'alolan', 'Alolan', 'regional', '', false, 'SWSH', '037_Vulpix_Alolan_Normal_Front.gif', false),
  (37, 'alolan', 'Alolan', 'regional', '', true, 'SWSH', '037_Vulpix_Alolan_Shiny_Front.gif', false),
  (37, 'base', 'Base', 'base', '', false, 'SWSH', '037_Vulpix_Base_Normal_Front.gif', true),
  (37, 'base', 'Base', 'base', '', true, 'SWSH', '037_Vulpix_Base_Shiny_Front.gif', true),
  (38, 'alolan', 'Alolan', 'regional', '', false, 'SWSH', '038_Ninetales_Alolan_Normal_Front.gif', false),
  (38, 'alolan', 'Alolan', 'regional', '', true, 'SWSH', '038_Ninetales_Alolan_Shiny_Front.gif', false),
  (38, 'base', 'Base', 'base', '', false, 'SWSH', '038_Ninetales_Base_Normal_Front.gif', true),
  (38, 'base', 'Base', 'base', '', true, 'SWSH', '038_Ninetales_Base_Shiny_Front.gif', true),
  (39, 'base', 'Base', 'base', '', false, 'Legacy3D', '039_Jigglypuff_Base_Normal_Front.gif', true),
  (39, 'base', 'Base', 'base', '', true, 'Legacy3D', '039_Jigglypuff_Base_Shiny_Front.gif', true),
  (40, 'base', 'Base', 'base', '', false, 'Legacy3D', '040_Wigglytuff_Base_Normal_Front.gif', true),
  (40, 'base', 'Base', 'base', '', true, 'Legacy3D', '040_Wigglytuff_Base_Shiny_Front.gif', true),
  (41, 'base', 'Base', 'base', 'female', false, 'Legacy3D', '041_Zubat_Base_Female_Normal_Front.gif', true),
  (41, 'base', 'Base', 'base', 'female', true, 'Legacy3D', '041_Zubat_Base_Female_Shiny_Front.gif', true),
  (41, 'base', 'Base', 'base', 'male', false, 'Legacy3D', '041_Zubat_Base_Male_Normal_Front.gif', true),
  (41, 'base', 'Base', 'base', 'male', true, 'Legacy3D', '041_Zubat_Base_Male_Shiny_Front.gif', true),
  (42, 'base', 'Base', 'base', 'female', false, 'Legacy3D', '042_Golbat_Base_Female_Normal_Front.gif', true),
  (42, 'base', 'Base', 'base', 'female', true, 'Legacy3D', '042_Golbat_Base_Female_Shiny_Front.gif', true),
  (42, 'base', 'Base', 'base', 'male', false, 'Legacy3D', '042_Golbat_Base_Male_Normal_Front.gif', true),
  (42, 'base', 'Base', 'base', 'male', true, 'Legacy3D', '042_Golbat_Base_Male_Shiny_Front.gif', true),
  (43, 'base', 'Base', 'base', '', false, 'SWSH', '043_Oddish_Base_Normal_Front.gif', true),
  (43, 'base', 'Base', 'base', '', true, 'SWSH', '043_Oddish_Base_Shiny_Front.gif', true),
  (44, 'base', 'Base', 'base', 'male', false, 'SWSH', '044_Gloom_Base_Male_Normal_Front.gif', true),
  (44, 'base', 'Base', 'base', 'male', true, 'SWSH', '044_Gloom_Base_Male_Shiny_Front.gif', true),
  (45, 'base', 'Base', 'base', 'male', false, 'SWSH', '045_Vileplume_Base_Male_Normal_Front.gif', true),
  (45, 'base', 'Base', 'base', 'male', true, 'SWSH', '045_Vileplume_Base_Male_Shiny_Front.gif', true),
  (46, 'base', 'Base', 'base', '', false, 'Legacy3D', '046_Paras_Base_Normal_Front.gif', true),
  (46, 'base', 'Base', 'base', '', true, 'Legacy3D', '046_Paras_Base_Shiny_Front.gif', true),
  (47, 'base', 'Base', 'base', '', false, 'Legacy3D', '047_Parasect_Base_Normal_Front.gif', true),
  (47, 'base', 'Base', 'base', '', true, 'Legacy3D', '047_Parasect_Base_Shiny_Front.gif', true),
  (48, 'base', 'Base', 'base', '', false, 'Legacy3D', '048_Venonat_Base_Normal_Front.gif', true),
  (48, 'base', 'Base', 'base', '', true, 'Legacy3D', '048_Venonat_Base_Shiny_Front.gif', true),
  (49, 'base', 'Base', 'base', '', false, 'Legacy3D', '049_Venomoth_Base_Normal_Front.gif', true),
  (49, 'base', 'Base', 'base', '', true, 'Legacy3D', '049_Venomoth_Base_Shiny_Front.gif', true),
  (50, 'alolan', 'Alolan', 'regional', '', false, 'SWSH', '050_Diglett_Alolan_Normal_Front.gif', false),
  (50, 'alolan', 'Alolan', 'regional', '', true, 'SWSH', '050_Diglett_Alolan_Shiny_Front.gif', false),
  (50, 'base', 'Base', 'base', '', false, 'SWSH', '050_Diglett_Base_Normal_Front.gif', true),
  (50, 'base', 'Base', 'base', '', true, 'SWSH', '050_Diglett_Base_Shiny_Front.gif', true),
  (51, 'alolan', 'Alolan', 'regional', '', false, 'SWSH', '051_Dugtrio_Alolan_Normal_Front.gif', false),
  (51, 'alolan', 'Alolan', 'regional', '', true, 'SWSH', '051_Dugtrio_Alolan_Shiny_Front.gif', false),
  (51, 'base', 'Base', 'base', '', false, 'SWSH', '051_Dugtrio_Base_Normal_Front.gif', true),
  (51, 'base', 'Base', 'base', '', true, 'SWSH', '051_Dugtrio_Base_Shiny_Front.gif', true),
  (52, 'alolan', 'Alolan', 'regional', '', false, 'SWSH', '052_Meowth_Alolan_Normal_Front.gif', false),
  (52, 'alolan', 'Alolan', 'regional', '', true, 'SWSH', '052_Meowth_Alolan_Shiny_Front.gif', false),
  (52, 'base', 'Base', 'base', '', false, 'SWSH', '052_Meowth_Base_Normal_Front.gif', true),
  (52, 'base', 'Base', 'base', '', true, 'SWSH', '052_Meowth_Base_Shiny_Front.gif', true),
  (52, 'galarian', 'Galarian', 'regional', '', false, 'SWSH', '052_Meowth_Galarian_Normal_Front.gif', false),
  (52, 'galarian', 'Galarian', 'regional', '', true, 'SWSH', '052_Meowth_Galarian_Shiny_Front.gif', false),
  (52, 'gigantamax', 'Gigantamax', 'gigantamax', '', false, 'SWSH', '052_Meowth_Gigantamax_Normal_Front.gif', false),
  (52, 'gigantamax', 'Gigantamax', 'gigantamax', '', true, 'SWSH', '052_Meowth_Gigantamax_Shiny_Front.gif', false),
  (53, 'alolan', 'Alolan', 'regional', '', false, 'SWSH', '053_Persian_Alolan_Normal_Front.gif', false),
  (53, 'alolan', 'Alolan', 'regional', '', true, 'SWSH', '053_Persian_Alolan_Shiny_Front.gif', false),
  (53, 'base', 'Base', 'base', '', false, 'SWSH', '053_Persian_Base_Normal_Front.gif', true),
  (53, 'base', 'Base', 'base', '', true, 'SWSH', '053_Persian_Base_Shiny_Front.gif', true),
  (54, 'base', 'Base', 'base', '', false, 'Legacy3D', '054_Psyduck_Base_Normal_Front.gif', true),
  (54, 'base', 'Base', 'base', '', true, 'Legacy3D', '054_Psyduck_Base_Shiny_Front.gif', true),
  (55, 'base', 'Base', 'base', '', false, 'Legacy3D', '055_Golduck_Base_Normal_Front.gif', true),
  (55, 'base', 'Base', 'base', '', true, 'Legacy3D', '055_Golduck_Base_Shiny_Front.gif', true),
  (56, 'base', 'Base', 'base', '', false, 'Legacy3D', '056_Mankey_Base_Normal_Front.gif', true),
  (56, 'base', 'Base', 'base', '', true, 'Legacy3D', '056_Mankey_Base_Shiny_Front.gif', true),
  (57, 'base', 'Base', 'base', '', false, 'Legacy3D', '057_Primeape_Base_Normal_Front.gif', true),
  (57, 'base', 'Base', 'base', '', true, 'Legacy3D', '057_Primeape_Base_Shiny_Front.gif', true),
  (58, 'base', 'Base', 'base', '', false, 'SWSH', '058_Growlithe_Base_Normal_Front.gif', true),
  (58, 'base', 'Base', 'base', '', true, 'SWSH', '058_Growlithe_Base_Shiny_Front.gif', true),
  (59, 'base', 'Base', 'base', '', false, 'SWSH', '059_Arcanine_Base_Normal_Front.gif', true),
  (59, 'base', 'Base', 'base', '', true, 'SWSH', '059_Arcanine_Base_Shiny_Front.gif', true),
  (60, 'base', 'Base', 'base', '', false, 'Legacy3D', '060_Poliwag_Base_Normal_Front.gif', true),
  (60, 'base', 'Base', 'base', '', true, 'Legacy3D', '060_Poliwag_Base_Shiny_Front.gif', true),
  (61, 'base', 'Base', 'base', '', false, 'Legacy3D', '061_Poliwhirl_Base_Normal_Front.gif', true),
  (61, 'base', 'Base', 'base', '', true, 'Legacy3D', '061_Poliwhirl_Base_Shiny_Front.gif', true),
  (62, 'base', 'Base', 'base', '', false, 'Legacy3D', '062_Poliwrath_Base_Normal_Front.gif', true),
  (62, 'base', 'Base', 'base', '', true, 'Legacy3D', '062_Poliwrath_Base_Shiny_Front.gif', true),
  (63, 'base', 'Base', 'base', '', false, 'Legacy3D', '063_Abra_Base_Normal_Front.gif', true),
  (63, 'base', 'Base', 'base', '', true, 'Legacy3D', '063_Abra_Base_Shiny_Front.gif', true),
  (64, 'base', 'Base', 'base', 'female', false, 'Legacy3D', '064_Kadabra_Base_Female_Normal_Front.gif', true),
  (64, 'base', 'Base', 'base', 'female', true, 'Legacy3D', '064_Kadabra_Base_Female_Shiny_Front.gif', true),
  (64, 'base', 'Base', 'base', 'male', false, 'Legacy3D', '064_Kadabra_Base_Male_Normal_Front.gif', true),
  (64, 'base', 'Base', 'base', 'male', true, 'Legacy3D', '064_Kadabra_Base_Male_Shiny_Front.gif', true),
  (65, 'base', 'Base', 'base', 'female', false, 'Legacy3D', '065_Alakazam_Base_Female_Normal_Front.gif', true),
  (65, 'base', 'Base', 'base', 'female', true, 'Legacy3D', '065_Alakazam_Base_Female_Shiny_Front.gif', true),
  (65, 'base', 'Base', 'base', 'male', false, 'Legacy3D', '065_Alakazam_Base_Male_Normal_Front.gif', true),
  (65, 'base', 'Base', 'base', 'male', true, 'Legacy3D', '065_Alakazam_Base_Male_Shiny_Front.gif', true),
  (65, 'mega', 'Mega', 'mega', '', false, 'Legacy3D', '065_Alakazam_Mega_Normal_Front.gif', false),
  (65, 'mega', 'Mega', 'mega', '', true, 'Legacy3D', '065_Alakazam_Mega_Shiny_Front.gif', false),
  (66, 'base', 'Base', 'base', '', false, 'SWSH', '066_Machop_Base_Normal_Front.gif', true),
  (66, 'base', 'Base', 'base', '', true, 'SWSH', '066_Machop_Base_Shiny_Front.gif', true),
  (67, 'base', 'Base', 'base', '', false, 'SWSH', '067_Machoke_Base_Normal_Front.gif', true),
  (67, 'base', 'Base', 'base', '', true, 'SWSH', '067_Machoke_Base_Shiny_Front.gif', true),
  (68, 'base', 'Base', 'base', '', false, 'SWSH', '068_Machamp_Base_Normal_Front.gif', true),
  (68, 'base', 'Base', 'base', '', true, 'SWSH', '068_Machamp_Base_Shiny_Front.gif', true),
  (68, 'gigantamax', 'Gigantamax', 'gigantamax', '', false, 'SWSH', '068_Machamp_Gigantamax_Normal_Front.gif', false),
  (68, 'gigantamax', 'Gigantamax', 'gigantamax', '', true, 'SWSH', '068_Machamp_Gigantamax_Shiny_Front.gif', false),
  (69, 'base', 'Base', 'base', '', false, 'Legacy3D', '069_Bellsprout_Base_Normal_Front.gif', true),
  (69, 'base', 'Base', 'base', '', true, 'Legacy3D', '069_Bellsprout_Base_Shiny_Front.gif', true),
  (70, 'base', 'Base', 'base', '', false, 'Legacy3D', '070_Weepinbell_Base_Normal_Front.gif', true),
  (70, 'base', 'Base', 'base', '', true, 'Legacy3D', '070_Weepinbell_Base_Shiny_Front.gif', true),
  (71, 'base', 'Base', 'base', '', false, 'Legacy3D', '071_Victreebel_Base_Normal_Front.gif', true),
  (71, 'base', 'Base', 'base', '', true, 'Legacy3D', '071_Victreebel_Base_Shiny_Front.gif', true),
  (72, 'base', 'Base', 'base', '', false, 'Legacy3D', '072_Tentacool_Base_Normal_Front.gif', true),
  (72, 'base', 'Base', 'base', '', true, 'Legacy3D', '072_Tentacool_Base_Shiny_Front.gif', true),
  (73, 'base', 'Base', 'base', '', false, 'Legacy3D', '073_Tentacruel_Base_Normal_Front.gif', true),
  (73, 'base', 'Base', 'base', '', true, 'Legacy3D', '073_Tentacruel_Base_Shiny_Front.gif', true),
  (74, 'alolan', 'Alolan', 'regional', '', false, 'Legacy3D', '074_Geodude_Alolan_Normal_Front.gif', false),
  (74, 'alolan', 'Alolan', 'regional', '', true, 'Legacy3D', '074_Geodude_Alolan_Shiny_Front.gif', false),
  (74, 'base', 'Base', 'base', '', false, 'Legacy3D', '074_Geodude_Base_Normal_Front.gif', true),
  (74, 'base', 'Base', 'base', '', true, 'Legacy3D', '074_Geodude_Base_Shiny_Front.gif', true),
  (75, 'alolan', 'Alolan', 'regional', '', false, 'Legacy3D', '075_Graveler_Alolan_Normal_Front.gif', false),
  (75, 'alolan', 'Alolan', 'regional', '', true, 'Legacy3D', '075_Graveler_Alolan_Shiny_Front.gif', false),
  (75, 'base', 'Base', 'base', '', false, 'Legacy3D', '075_Graveler_Base_Normal_Front.gif', true),
  (75, 'base', 'Base', 'base', '', true, 'Legacy3D', '075_Graveler_Base_Shiny_Front.gif', true),
  (76, 'alolan', 'Alolan', 'regional', '', false, 'Legacy3D', '076_Golem_Alolan_Normal_Front.gif', false),
  (76, 'alolan', 'Alolan', 'regional', '', true, 'Legacy3D', '076_Golem_Alolan_Shiny_Front.gif', false),
  (76, 'base', 'Base', 'base', '', false, 'Legacy3D', '076_Golem_Base_Normal_Front.gif', true),
  (76, 'base', 'Base', 'base', '', true, 'Legacy3D', '076_Golem_Base_Shiny_Front.gif', true),
  (77, 'base', 'Base', 'base', '', false, 'SWSH', '077_Ponyta_Base_Normal_Front.gif', true),
  (77, 'base', 'Base', 'base', '', true, 'SWSH', '077_Ponyta_Base_Shiny_Front.gif', true),
  (77, 'galarian', 'Galarian', 'regional', '', false, 'SWSH', '077_Ponyta_Galarian_Normal_Front.gif', false),
  (77, 'galarian', 'Galarian', 'regional', '', true, 'SWSH', '077_Ponyta_Galarian_Shiny_Front.gif', false),
  (78, 'base', 'Base', 'base', '', false, 'SWSH', '078_Rapidash_Base_Normal_Front.gif', true),
  (78, 'base', 'Base', 'base', '', true, 'SWSH', '078_Rapidash_Base_Shiny_Front.gif', true),
  (78, 'galarian', 'Galarian', 'regional', '', false, 'SWSH', '078_Rapidash_Galarian_Normal_Front.gif', false),
  (78, 'galarian', 'Galarian', 'regional', '', true, 'SWSH', '078_Rapidash_Galarian_Shiny_Front.gif', false),
  (79, 'galarian', 'Galarian', 'regional', '', false, 'SWSH', '079_Slowpoke_Galarian_Normal_Front.gif', false),
  (79, 'galarian', 'Galarian', 'regional', '', true, 'SWSH', '079_Slowpoke_Galarian_Shiny_Front.gif', false),
  (79, 'base', 'Base', 'base', '', false, 'Legacy3D', '079_Slowpoke_Base_Normal_Front.gif', true),
  (79, 'base', 'Base', 'base', '', true, 'Legacy3D', '079_Slowpoke_Base_Shiny_Front.gif', true),
  (80, 'galarian', 'Galarian', 'regional', '', false, 'SWSH', '080_Slowbro_Galarian_Normal_Front.gif', false),
  (80, 'galarian', 'Galarian', 'regional', '', true, 'SWSH', '080_Slowbro_Galarian_Shiny_Front.gif', false),
  (80, 'base', 'Base', 'base', '', false, 'Legacy3D', '080_Slowbro_Base_Normal_Front.gif', true),
  (80, 'base', 'Base', 'base', '', true, 'Legacy3D', '080_Slowbro_Base_Shiny_Front.gif', true),
  (80, 'mega', 'Mega', 'mega', '', false, 'Legacy3D', '080_Slowbro_Mega_Normal_Front.gif', false),
  (80, 'mega', 'Mega', 'mega', '', true, 'Legacy3D', '080_Slowbro_Mega_Shiny_Front.gif', false),
  (81, 'base', 'Base', 'base', '', false, 'Legacy3D', '081_Magnemite_Base_Normal_Front.gif', true),
  (81, 'base', 'Base', 'base', '', true, 'Legacy3D', '081_Magnemite_Base_Shiny_Front.gif', true),
  (82, 'base', 'Base', 'base', '', false, 'Legacy3D', '082_Magneton_Base_Normal_Front.gif', true),
  (82, 'base', 'Base', 'base', '', true, 'Legacy3D', '082_Magneton_Base_Shiny_Front.gif', true),
  (83, 'base', 'Base', 'base', '', false, 'SWSH', '083_Farfetchd_Base_Normal_Front.gif', true),
  (83, 'base', 'Base', 'base', '', true, 'SWSH', '083_Farfetchd_Base_Shiny_Front.gif', true),
  (83, 'galarian', 'Galarian', 'regional', '', false, 'SWSH', '083_Farfetchd_Galarian_Normal_Front.gif', false),
  (83, 'galarian', 'Galarian', 'regional', '', true, 'SWSH', '083_Farfetchd_Galarian_Shiny_Front.gif', false),
  (84, 'base', 'Base', 'base', 'female', false, 'Legacy3D', '084_Doduo_Base_Female_Normal_Front.gif', true),
  (84, 'base', 'Base', 'base', 'female', true, 'Legacy3D', '084_Doduo_Base_Female_Shiny_Front.gif', true),
  (84, 'base', 'Base', 'base', 'male', false, 'Legacy3D', '084_Doduo_Base_Male_Normal_Front.gif', true),
  (84, 'base', 'Base', 'base', 'male', true, 'Legacy3D', '084_Doduo_Base_Male_Shiny_Front.gif', true),
  (85, 'base', 'Base', 'base', 'female', false, 'Legacy3D', '085_Dodrio_Base_Female_Normal_Front.gif', true),
  (85, 'base', 'Base', 'base', 'female', true, 'Legacy3D', '085_Dodrio_Base_Female_Shiny_Front.gif', true),
  (85, 'base', 'Base', 'base', 'male', false, 'Legacy3D', '085_Dodrio_Base_Male_Normal_Front.gif', true),
  (85, 'base', 'Base', 'base', 'male', true, 'Legacy3D', '085_Dodrio_Base_Male_Shiny_Front.gif', true),
  (86, 'base', 'Base', 'base', '', false, 'Legacy3D', '086_Seel_Base_Normal_Front.gif', true),
  (86, 'base', 'Base', 'base', '', true, 'Legacy3D', '086_Seel_Base_Shiny_Front.gif', true),
  (87, 'base', 'Base', 'base', '', false, 'Legacy3D', '087_Dewgong_Base_Normal_Front.gif', true),
  (87, 'base', 'Base', 'base', '', true, 'Legacy3D', '087_Dewgong_Base_Shiny_Front.gif', true),
  (88, 'alolan', 'Alolan', 'regional', '', false, 'Legacy3D', '088_Grimer_Alolan_Normal_Front.gif', false),
  (88, 'alolan', 'Alolan', 'regional', '', true, 'Legacy3D', '088_Grimer_Alolan_Shiny_Front.gif', false),
  (88, 'base', 'Base', 'base', '', false, 'Legacy3D', '088_Grimer_Base_Normal_Front.gif', true),
  (88, 'base', 'Base', 'base', '', true, 'Legacy3D', '088_Grimer_Base_Shiny_Front.gif', true),
  (89, 'alolan', 'Alolan', 'regional', '', false, 'Legacy3D', '089_Muk_Alolan_Normal_Front.gif', false),
  (89, 'alolan', 'Alolan', 'regional', '', true, 'Legacy3D', '089_Muk_Alolan_Shiny_Front.gif', false),
  (89, 'base', 'Base', 'base', '', false, 'Legacy3D', '089_Muk_Base_Normal_Front.gif', true),
  (89, 'base', 'Base', 'base', '', true, 'Legacy3D', '089_Muk_Base_Shiny_Front.gif', true),
  (90, 'base', 'Base', 'base', '', false, 'SWSH', '090_Shellder_Base_Normal_Front.gif', true),
  (90, 'base', 'Base', 'base', '', true, 'SWSH', '090_Shellder_Base_Shiny_Front.gif', true),
  (91, 'base', 'Base', 'base', '', false, 'SWSH', '091_Cloyster_Base_Normal_Front.gif', true),
  (91, 'base', 'Base', 'base', '', true, 'SWSH', '091_Cloyster_Base_Shiny_Front.gif', true),
  (92, 'base', 'Base', 'base', '', false, 'SWSH', '092_Gastly_Base_Normal_Front.gif', true),
  (92, 'base', 'Base', 'base', '', true, 'SWSH', '092_Gastly_Base_Shiny_Front.gif', true),
  (93, 'base', 'Base', 'base', '', false, 'SWSH', '093_Haunter_Base_Normal_Front.gif', true),
  (93, 'base', 'Base', 'base', '', true, 'SWSH', '093_Haunter_Base_Shiny_Front.gif', true),
  (94, 'base', 'Base', 'base', '', false, 'SWSH', '094_Gengar_Base_Normal_Front.gif', true),
  (94, 'base', 'Base', 'base', '', true, 'SWSH', '094_Gengar_Base_Shiny_Front.gif', true),
  (94, 'gigantamax', 'Gigantamax', 'gigantamax', '', false, 'SWSH', '094_Gengar_Gigantamax_Normal_Front.gif', false),
  (94, 'gigantamax', 'Gigantamax', 'gigantamax', '', true, 'SWSH', '094_Gengar_Gigantamax_Shiny_Front.gif', false),
  (94, 'mega', 'Mega', 'mega', '', false, 'Legacy3D', '094_Gengar_Mega_Normal_Front.gif', false),
  (94, 'mega', 'Mega', 'mega', '', true, 'Legacy3D', '094_Gengar_Mega_Shiny_Front.gif', false),
  (95, 'base', 'Base', 'base', '', false, 'SWSH', '095_Onix_Base_Normal_Front.gif', true),
  (95, 'base', 'Base', 'base', '', true, 'SWSH', '095_Onix_Base_Shiny_Front.gif', true),
  (96, 'base', 'Base', 'base', '', false, 'Legacy3D', '096_Drowzee_Base_Normal_Front.gif', true),
  (96, 'base', 'Base', 'base', '', true, 'Legacy3D', '096_Drowzee_Base_Shiny_Front.gif', true),
  (97, 'base', 'Base', 'base', 'female', false, 'Legacy3D', '097_Hypno_Base_Female_Normal_Front.gif', true),
  (97, 'base', 'Base', 'base', 'female', true, 'Legacy3D', '097_Hypno_Base_Female_Shiny_Front.gif', true),
  (97, 'base', 'Base', 'base', 'male', false, 'Legacy3D', '097_Hypno_Base_Male_Normal_Front.gif', true),
  (97, 'base', 'Base', 'base', 'male', true, 'Legacy3D', '097_Hypno_Base_Male_Shiny_Front.gif', true),
  (98, 'base', 'Base', 'base', '', false, 'SWSH', '098_Krabby_Base_Normal_Front.gif', true),
  (98, 'base', 'Base', 'base', '', true, 'SWSH', '098_Krabby_Base_Shiny_Front.gif', true),
  (99, 'base', 'Base', 'base', '', false, 'SWSH', '099_Kingler_Base_Normal_Front.gif', true),
  (99, 'base', 'Base', 'base', '', true, 'SWSH', '099_Kingler_Base_Shiny_Front.gif', true),
  (99, 'gigantamax', 'Gigantamax', 'gigantamax', '', false, 'SWSH', '099_Kingler_Gigantamax_Normal_Front.gif', false),
  (99, 'gigantamax', 'Gigantamax', 'gigantamax', '', true, 'SWSH', '099_Kingler_Gigantamax_Shiny_Front.gif', false),
  (100, 'base', 'Base', 'base', '', false, 'Legacy3D', '100_Voltorb_Base_Normal_Front.gif', true),
  (100, 'base', 'Base', 'base', '', true, 'Legacy3D', '100_Voltorb_Base_Shiny_Front.gif', true),
  (101, 'base', 'Base', 'base', '', false, 'Legacy3D', '101_Electrode_Base_Normal_Front.gif', true),
  (101, 'base', 'Base', 'base', '', true, 'Legacy3D', '101_Electrode_Base_Shiny_Front.gif', true),
  (102, 'base', 'Base', 'base', '', false, 'Legacy3D', '102_Exeggcute_Base_Normal_Front.gif', true),
  (102, 'base', 'Base', 'base', '', true, 'Legacy3D', '102_Exeggcute_Base_Shiny_Front.gif', true),
  (103, 'alolan', 'Alolan', 'regional', '', false, 'Legacy3D', '103_Exeggutor_Alolan_Normal_Front.gif', false),
  (103, 'alolan', 'Alolan', 'regional', '', true, 'Legacy3D', '103_Exeggutor_Alolan_Shiny_Front.gif', false),
  (103, 'base', 'Base', 'base', '', false, 'Legacy3D', '103_Exeggutor_Base_Normal_Front.gif', true),
  (103, 'base', 'Base', 'base', '', true, 'Legacy3D', '103_Exeggutor_Base_Shiny_Front.gif', true),
  (104, 'base', 'Base', 'base', '', false, 'Legacy3D', '104_Cubone_Base_Normal_Front.gif', true),
  (104, 'base', 'Base', 'base', '', true, 'Legacy3D', '104_Cubone_Base_Shiny_Front.gif', true),
  (105, 'alolan', 'Alolan', 'regional', '', false, 'Legacy3D', '105_Marowak_Alolan_Normal_Front.gif', false),
  (105, 'alolan', 'Alolan', 'regional', '', true, 'Legacy3D', '105_Marowak_Alolan_Shiny_Front.gif', false),
  (105, 'base', 'Base', 'base', '', false, 'Legacy3D', '105_Marowak_Base_Normal_Front.gif', true),
  (105, 'base', 'Base', 'base', '', true, 'Legacy3D', '105_Marowak_Base_Shiny_Front.gif', true),
  (105, 'totem', 'Totem', 'other', '', false, 'Legacy3D', '105_Marowak_Totem_Normal_Front.gif', false),
  (105, 'totem', 'Totem', 'other', '', true, 'Legacy3D', '105_Marowak_Totem_Shiny_Front.gif', false),
  (106, 'base', 'Base', 'base', '', false, 'SWSH', '106_Hitmonlee_Base_Normal_Front.gif', true),
  (106, 'base', 'Base', 'base', '', true, 'SWSH', '106_Hitmonlee_Base_Shiny_Front.gif', true),
  (107, 'base', 'Base', 'base', '', false, 'SWSH', '107_Hitmonchan_Base_Normal_Front.gif', true),
  (107, 'base', 'Base', 'base', '', true, 'SWSH', '107_Hitmonchan_Base_Shiny_Front.gif', true),
  (108, 'base', 'Base', 'base', '', false, 'Legacy3D', '108_Lickitung_Base_Normal_Front.gif', true),
  (108, 'base', 'Base', 'base', '', true, 'Legacy3D', '108_Lickitung_Base_Shiny_Front.gif', true),
  (109, 'base', 'Base', 'base', '', false, 'SWSH', '109_Koffing_Base_Normal_Front.gif', true),
  (109, 'base', 'Base', 'base', '', true, 'SWSH', '109_Koffing_Base_Shiny_Front.gif', true),
  (110, 'base', 'Base', 'base', '', false, 'SWSH', '110_Weezing_Base_Normal_Front.gif', true),
  (110, 'base', 'Base', 'base', '', true, 'SWSH', '110_Weezing_Base_Shiny_Front.gif', true),
  (110, 'galarian', 'Galarian', 'regional', '', false, 'SWSH', '110_Weezing_Galarian_Normal_Front.gif', false),
  (110, 'galarian', 'Galarian', 'regional', '', true, 'SWSH', '110_Weezing_Galarian_Shiny_Front.gif', false),
  (111, 'base', 'Base', 'base', 'male', false, 'SWSH', '111_Rhyhorn_Base_Male_Normal_Front.gif', true),
  (111, 'base', 'Base', 'base', 'male', true, 'SWSH', '111_Rhyhorn_Base_Male_Shiny_Front.gif', true),
  (112, 'base', 'Base', 'base', 'male', false, 'SWSH', '112_Rhydon_Base_Male_Normal_Front.gif', true),
  (112, 'base', 'Base', 'base', 'male', true, 'SWSH', '112_Rhydon_Base_Male_Shiny_Front.gif', true),
  (113, 'base', 'Base', 'base', '', false, 'Legacy3D', '113_Chansey_Base_Normal_Front.gif', true),
  (113, 'base', 'Base', 'base', '', true, 'Legacy3D', '113_Chansey_Base_Shiny_Front.gif', true),
  (114, 'base', 'Base', 'base', '', false, 'Legacy3D', '114_Tangela_Base_Normal_Front.gif', true),
  (114, 'base', 'Base', 'base', '', true, 'Legacy3D', '114_Tangela_Base_Shiny_Front.gif', true),
  (115, 'base', 'Base', 'base', '', false, 'Legacy3D', '115_Kangaskhan_Base_Normal_Front.gif', true),
  (115, 'base', 'Base', 'base', '', true, 'Legacy3D', '115_Kangaskhan_Base_Shiny_Front.gif', true),
  (115, 'mega', 'Mega', 'mega', '', false, 'Legacy3D', '115_Kangaskhan_Mega_Normal_Front.gif', false),
  (115, 'mega', 'Mega', 'mega', '', true, 'Legacy3D', '115_Kangaskhan_Mega_Shiny_Front.gif', false),
  (116, 'base', 'Base', 'base', '', false, 'Legacy3D', '116_Horsea_Base_Normal_Front.gif', true),
  (116, 'base', 'Base', 'base', '', true, 'Legacy3D', '116_Horsea_Base_Shiny_Front.gif', true),
  (117, 'base', 'Base', 'base', '', false, 'Legacy3D', '117_Seadra_Base_Normal_Front.gif', true),
  (117, 'base', 'Base', 'base', '', true, 'Legacy3D', '117_Seadra_Base_Shiny_Front.gif', true),
  (118, 'base', 'Base', 'base', 'male', false, 'SWSH', '118_Goldeen_Base_Male_Normal_Front.gif', true),
  (118, 'base', 'Base', 'base', 'male', true, 'SWSH', '118_Goldeen_Base_Male_Shiny_Front.gif', true),
  (119, 'base', 'Base', 'base', 'male', false, 'SWSH', '119_Seaking_Base_Male_Normal_Front.gif', true),
  (119, 'base', 'Base', 'base', 'male', true, 'SWSH', '119_Seaking_Base_Male_Shiny_Front.gif', true),
  (120, 'base', 'Base', 'base', '', false, 'Legacy3D', '120_Staryu_Base_Normal_Front.gif', true),
  (120, 'base', 'Base', 'base', '', true, 'Legacy3D', '120_Staryu_Base_Shiny_Front.gif', true),
  (121, 'base', 'Base', 'base', '', false, 'Legacy3D', '121_Starmie_Base_Normal_Front.gif', true),
  (121, 'base', 'Base', 'base', '', true, 'Legacy3D', '121_Starmie_Base_Shiny_Front.gif', true),
  (122, 'base', 'Base', 'base', '', false, 'Legacy3D', '122_MrMime_Base_Normal_Front.gif', true),
  (122, 'base', 'Base', 'base', '', true, 'Legacy3D', '122_MrMime_Base_Normal_Front.gif', true),
  (123, 'base', 'Base', 'base', 'female', false, 'Legacy3D', '123_Scyther_Base_Female_Normal_Front.gif', true),
  (123, 'base', 'Base', 'base', 'female', true, 'Legacy3D', '123_Scyther_Base_Female_Shiny_Front.gif', true),
  (123, 'base', 'Base', 'base', 'male', false, 'Legacy3D', '123_Scyther_Base_Male_Normal_Front.gif', true),
  (123, 'base', 'Base', 'base', 'male', true, 'Legacy3D', '123_Scyther_Base_Male_Shiny_Front.gif', true),
  (124, 'base', 'Base', 'base', '', false, 'Legacy3D', '124_Jynx_Base_Normal_Front.gif', true),
  (124, 'base', 'Base', 'base', '', true, 'Legacy3D', '124_Jynx_Base_Shiny_Front.gif', true),
  (125, 'base', 'Base', 'base', '', false, 'Legacy3D', '125_Electabuzz_Base_Normal_Front.gif', true),
  (125, 'base', 'Base', 'base', '', true, 'Legacy3D', '125_Electabuzz_Base_Shiny_Front.gif', true),
  (126, 'base', 'Base', 'base', '', false, 'Legacy3D', '126_Magmar_Base_Normal_Front.gif', true),
  (126, 'base', 'Base', 'base', '', true, 'Legacy3D', '126_Magmar_Base_Shiny_Front.gif', true),
  (127, 'base', 'Base', 'base', '', false, 'Legacy3D', '127_Pinsir_Base_Normal_Front.gif', true),
  (127, 'base', 'Base', 'base', '', true, 'Legacy3D', '127_Pinsir_Base_Shiny_Front.gif', true),
  (127, 'mega', 'Mega', 'mega', '', false, 'Legacy3D', '127_Pinsir_Mega_Normal_Front.gif', false),
  (127, 'mega', 'Mega', 'mega', '', true, 'Legacy3D', '127_Pinsir_Mega_Shiny_Front.gif', false),
  (128, 'base', 'Base', 'base', '', false, 'Legacy3D', '128_Tauros_Base_Normal_Front.gif', true),
  (128, 'base', 'Base', 'base', '', true, 'Legacy3D', '128_Tauros_Base_Shiny_Front.gif', true),
  (129, 'base', 'Base', 'base', 'male', false, 'SWSH', '129_Magikarp_Base_Male_Normal_Front.gif', true),
  (129, 'base', 'Base', 'base', 'male', true, 'SWSH', '129_Magikarp_Base_Male_Shiny_Front.gif', true),
  (130, 'base', 'Base', 'base', 'male', false, 'SWSH', '130_Gyarados_Base_Male_Normal_Front.gif', true),
  (130, 'base', 'Base', 'base', 'male', true, 'SWSH', '130_Gyarados_Base_Male_Shiny_Front.gif', true),
  (130, 'mega', 'Mega', 'mega', '', false, 'Legacy3D', '130_Gyarados_Mega_Normal_Front.gif', false),
  (130, 'mega', 'Mega', 'mega', '', true, 'Legacy3D', '130_Gyarados_Mega_Shiny_Front.gif', false),
  (131, 'base', 'Base', 'base', '', false, 'SWSH', '131_Lapras_Base_Normal_Front.gif', true),
  (131, 'base', 'Base', 'base', '', true, 'SWSH', '131_Lapras_Base_Shiny_Front.gif', true),
  (131, 'gigantamax', 'Gigantamax', 'gigantamax', '', false, 'SWSH', '131_Lapras_Gigantamax_Normal_Front.gif', false),
  (131, 'gigantamax', 'Gigantamax', 'gigantamax', '', true, 'SWSH', '131_Lapras_Gigantamax_Shiny_Front.gif', false),
  (132, 'base', 'Base', 'base', '', false, 'SWSH', '132_Ditto_Base_Normal_Front.gif', true),
  (132, 'base', 'Base', 'base', '', true, 'SWSH', '132_Ditto_Base_Shiny_Front.gif', true),
  (133, 'base', 'Base', 'base', '', false, 'SWSH', '133_Eevee_Base_Normal_Front.gif', true),
  (133, 'base', 'Base', 'base', '', true, 'SWSH', '133_Eevee_Base_Shiny_Front.gif', true),
  (133, 'gigantamax', 'Gigantamax', 'gigantamax', '', false, 'SWSH', '133_Eevee_Gigantamax_Normal_Front.gif', false),
  (133, 'gigantamax', 'Gigantamax', 'gigantamax', '', true, 'SWSH', '133_Eevee_Gigantamax_Shiny_Front.gif', false),
  (134, 'base', 'Base', 'base', '', false, 'SWSH', '134_Vaporeon_Base_Normal_Front.gif', true),
  (134, 'base', 'Base', 'base', '', true, 'SWSH', '134_Vaporeon_Base_Shiny_Front.gif', true),
  (135, 'base', 'Base', 'base', '', false, 'SWSH', '135_Jolteon_Base_Normal_Front.gif', true),
  (135, 'base', 'Base', 'base', '', true, 'SWSH', '135_Jolteon_Base_Shiny_Front.gif', true),
  (136, 'base', 'Base', 'base', '', false, 'SWSH', '136_Flareon_Base_Normal_Front.gif', true),
  (136, 'base', 'Base', 'base', '', true, 'SWSH', '136_Flareon_Base_Shiny_Front.gif', true),
  (137, 'base', 'Base', 'base', '', false, 'Legacy3D', '137_Porygon_Base_Normal_Front.gif', true),
  (137, 'base', 'Base', 'base', '', true, 'Legacy3D', '137_Porygon_Base_Shiny_Front.gif', true),
  (137, 'z', 'Z', 'other', '', false, 'Legacy3D', '137_Porygon_Z_Normal_Front.gif', false),
  (137, 'z', 'Z', 'other', '', true, 'Legacy3D', '137_Porygon_Z_Shiny_Front.gif', false),
  (138, 'base', 'Base', 'base', '', false, 'Legacy3D', '138_Omanyte_Base_Normal_Front.gif', true),
  (138, 'base', 'Base', 'base', '', true, 'Legacy3D', '138_Omanyte_Base_Shiny_Front.gif', true),
  (139, 'base', 'Base', 'base', '', false, 'Legacy3D', '139_Omastar_Base_Normal_Front.gif', true),
  (139, 'base', 'Base', 'base', '', true, 'Legacy3D', '139_Omastar_Base_Shiny_Front.gif', true),
  (140, 'base', 'Base', 'base', '', false, 'Legacy3D', '140_Kabuto_Base_Normal_Front.gif', true),
  (140, 'base', 'Base', 'base', '', true, 'Legacy3D', '140_Kabuto_Base_Shiny_Front.gif', true),
  (141, 'base', 'Base', 'base', '', false, 'Legacy3D', '141_Kabutops_Base_Normal_Front.gif', true),
  (141, 'base', 'Base', 'base', '', true, 'Legacy3D', '141_Kabutops_Base_Shiny_Front.gif', true),
  (142, 'base', 'Base', 'base', '', false, 'Legacy3D', '142_Aerodactyl_Base_Normal_Front.gif', true),
  (142, 'base', 'Base', 'base', '', true, 'Legacy3D', '142_Aerodactyl_Base_Shiny_Front.gif', true),
  (142, 'mega', 'Mega', 'mega', '', false, 'Legacy3D', '142_Aerodactyl_Mega_Normal_Front.gif', false),
  (142, 'mega', 'Mega', 'mega', '', true, 'Legacy3D', '142_Aerodactyl_Mega_Shiny_Front.gif', false),
  (143, 'base', 'Base', 'base', '', false, 'SWSH', '143_Snorlax_Base_Normal_Front.gif', true),
  (143, 'base', 'Base', 'base', '', true, 'SWSH', '143_Snorlax_Base_Shiny_Front.gif', true),
  (143, 'gigantamax', 'Gigantamax', 'gigantamax', '', false, 'SWSH', '143_Snorlax_Gigantamax_Normal_Front.gif', false),
  (143, 'gigantamax', 'Gigantamax', 'gigantamax', '', true, 'SWSH', '143_Snorlax_Gigantamax_Shiny_Front.gif', false),
  (144, 'base', 'Base', 'base', '', false, 'Legacy3D', '144_Articuno_Base_Normal_Front.gif', true),
  (144, 'base', 'Base', 'base', '', true, 'Legacy3D', '144_Articuno_Base_Shiny_Front.gif', true),
  (145, 'base', 'Base', 'base', '', false, 'Legacy3D', '145_Zapdos_Base_Normal_Front.gif', true),
  (145, 'base', 'Base', 'base', '', true, 'Legacy3D', '145_Zapdos_Base_Shiny_Front.gif', true),
  (146, 'base', 'Base', 'base', '', false, 'Legacy3D', '146_Moltres_Base_Normal_Front.gif', true),
  (146, 'base', 'Base', 'base', '', true, 'Legacy3D', '146_Moltres_Base_Shiny_Front.gif', true),
  (147, 'base', 'Base', 'base', '', false, 'Legacy3D', '147_Dratini_Base_Normal_Front.gif', true),
  (147, 'base', 'Base', 'base', '', true, 'Legacy3D', '147_Dratini_Base_Shiny_Front.gif', true),
  (148, 'base', 'Base', 'base', '', false, 'Legacy3D', '148_Dragonair_Base_Normal_Front.gif', true),
  (148, 'base', 'Base', 'base', '', true, 'Legacy3D', '148_Dragonair_Base_Shiny_Front.gif', true),
  (149, 'base', 'Base', 'base', '', false, 'Legacy3D', '149_Dragonite_Base_Normal_Front.gif', true),
  (149, 'base', 'Base', 'base', '', true, 'Legacy3D', '149_Dragonite_Base_Shiny_Front.gif', true),
  (150, 'base', 'Base', 'base', '', false, 'Legacy3D', '150_Mewtwo_Base_Normal_Front.gif', true),
  (150, 'base', 'Base', 'base', '', true, 'Legacy3D', '150_Mewtwo_Base_Shiny_Front.gif', true),
  (150, 'mega-x', 'Mega X', 'mega', '', false, 'Legacy3D', '150_Mewtwo_MegaX_Normal_Front.gif', false),
  (150, 'mega-x', 'Mega X', 'mega', '', true, 'Legacy3D', '150_Mewtwo_MegaX_Shiny_Front.gif', false),
  (150, 'mega-y', 'Mega Y', 'mega', '', false, 'Legacy3D', '150_Mewtwo_MegaY_Normal_Front.gif', false),
  (150, 'mega-y', 'Mega Y', 'mega', '', true, 'Legacy3D', '150_Mewtwo_MegaY_Shiny_Front.gif', false),
  (151, 'base', 'Base', 'base', '', false, 'Legacy3D', '151_Mew_Base_Normal_Front.gif', true),
  (151, 'base', 'Base', 'base', '', true, 'Legacy3D', '151_Mew_Base_Shiny_Front.gif', true)
on conflict (dex, form_key, gender, shiny) do update
set form_label = excluded.form_label,
    kind = excluded.kind,
    source_set = excluded.source_set,
    filename = excluded.filename,
    enabled_in_play = excluded.enabled_in_play;

create or replace function private.female_visual_dex()
returns int[]
language sql
stable
as $function$
  select coalesce(array_agg(dex order by dex), '{}'::int[])
  from (
    select distinct dex
    from public.species_forms
    where enabled_in_play
      and form_key = 'base'
      and gender = 'female'
      and not shiny
  ) s;
$function$;

create or replace function private.progression_self_test()
returns table(name text, passed boolean, detail text)
language plpgsql
as $function$
declare
  prog jsonb;
  uid uuid;
  xp1 int;
  xp2 int;
begin
  name := 'Level 1 needs no XP';
  passed := private.xp_to_reach_level(1) = 0;
  detail := private.xp_to_reach_level(1)::text;
  return next;

  name := 'Level 2 uses the configured curve';
  passed := private.xp_for_level(1) = 100;
  detail := private.xp_for_level(1)::text;
  return next;

  name := '100 XP is level 2';
  passed := private.trainer_level(100) = 2;
  detail := private.trainer_level(100)::text;
  return next;

  name := '99 XP is still level 1';
  passed := private.trainer_level(99) = 1;
  detail := private.trainer_level(99)::text;
  return next;

  prog := private.trainer_xp_progress(100);
  name := 'XP progress splits into / need';
  passed := (prog->>'xpInto')::int = 0 and (prog->>'xpNeed')::int = private.xp_for_level(2);
  detail := prog::text;
  return next;

  name := 'Variants do not inflate Kanto 151';
  passed := coalesce((private.collection_variant_stats(null)->>'kantoTotal')::int, 151) = 151;
  detail := '151';
  return next;

  name := 'Female visual list is data-driven';
  passed := cardinality(private.female_visual_dex()) = 11;
  detail := cardinality(private.female_visual_dex())::text;
  return next;

  name := 'Level catch bonus stays off';
  passed := coalesce((private.progression_config()->>'levelCatchBonus')::boolean, true) = false;
  detail := private.progression_config()->>'levelCatchBonus';
  return next;

  name := 'Master Ball is a 151 milestone option';
  passed := exists (
    select 1 from jsonb_array_elements(private.economy_config()->'dexMilestones') v
    where (v.value->>'species')::int = 151 and v.value->'grants' ? 'masterball'
  );
  detail := '151';
  return next;

  name := 'Achievement catalog is loaded';
  passed := (select count(*) >= 40 from public.progression_achievements);
  detail := (select count(*)::text from public.progression_achievements);
  return next;

  name := 'Grant XP is idempotent';
  select id, xp into uid, xp1 from public.profiles limit 1;
  if uid is null then
    passed := true;
    detail := 'no profile';
  else
    perform private.grant_xp(uid, 0, 'TEST', 'none',
      jsonb_build_object('idempotency', 'self-test-zero'));
    select xp into xp2 from public.profiles where id = uid;
    passed := xp1 = xp2;
    detail := xp1::text;
  end if;
  return next;
end;
$function$;
